### ISSUE TITLE
Murder infected the clown

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#100]
Когда зараженный убивает шута, то он может умереть, я полагаю, это не правильно, учитывая, что он появляется очень редко и он не видит роль шута, я думаю, надо отключить в его адрес правила и при убийства зараженным шута, шут должен стать просто зараженным, без его 5 правил.

**Comment by dok441** [comment]
Так же я заметил, что зараженные, которых заразили не могли зарезать шута.

**Comment by Alf21** [comment]
Alright. That's a bug. The jester should be converted into an infected.

**Comment by SchokoShampoo** [comment]
can you try again?
