### ISSUE TITLE
Dead purpose

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#101]
Я был неизвестным, меня убил хитман, я возродился и у меня показывается цель, которая умерла в самом начале раунда спрыгнув с высоты.
![233](https://user-images.githubusercontent.com/7480655/48678089-71b85280-eba0-11e8-8535-2aeb74eea7e1.png)

**Comment by Alf21** [comment]
Thanks for this screenshot. It's so much easier to solve problems in this way. It's definitely a bug!

**Comment by Alf21** [comment]
Okay, I checked and I was wrong. That's not a bug. Maybe this player revived.
