### ISSUE TITLE
jester bug end round

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#103]
Дело предстояло так, я захожу, 3 человека, думаю, что за дела, смотрю, осталось 3 человека, 2 предателя и 1 шут. Убиваю шута и раунд кончается. Замечу, шут упал вниз карты, где его было не достать, я думаю, почему, смотрю логи прошлого раунда, он был убит невиновным, каким образом он остался шутом я не знаю, так же остался бессмертным, я помню этот баг и видимо он остался все еще.
![2444](https://user-images.githubusercontent.com/7480655/48792784-faf19580-ed16-11e8-8a9c-bd82af2c3927.png)
![4444](https://user-images.githubusercontent.com/7480655/48792788-fc22c280-ed16-11e8-9c06-99fd1b53e78b.png)

**Comment by SchokoShampoo** [comment]
So, if only 2 Traitors and the Jester are left the round should end. But that isn't the case, right?

**Comment by Alf21** [comment]
hmm... At first, I will try to fix the logs

**Comment by SchokoShampoo** [comment]
So the reason the round didn't end was probably that he had a opposite role of the traitors.
The damalog is still a third-party addon, and we set our priorities to our own addons to let them work perfect. If we have some spare time left, we maybe get some work at the damagelog done

**Comment by dok441** [comment]
Но, почему он тогда не умер в пропасти? Он был шутом, спрыгнул в пропасть, где его было не достать, коли он был противоположной ролью, он обязан был умереть прыгнув туда, так-как бессмертие должно пропасть.

**Comment by SchokoShampoo** [comment]
We discussed this topic and decided, that the Jester can only be killed by other players, because he will win, if he goes suicide. So he will be immortal, expect an other player kills him.

**Comment by SchokoShampoo** [comment]
Maybe he jumped down there as a Jester and was killed when he was down there. So he didn't died through  fall damage

**Comment by SchokoShampoo** [comment]
so what should we do instead of saving him?
