### ISSUE TITLE
jester bug?

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#106]
Если не ошибаюсь, если ясновидящий убивает шута, он становится его сообщником, это все еще так? Так-как ясновидящий просто умер, а я стал вампиром после его убийства.

**Comment by Alf21** [comment]
With the normal win state, yes. But I don't know whether Schoko paid attention to this in his new win states.

**Comment by SchokoShampoo** [comment]
The clairvoyant died or the jester?

**Comment by dok441** [comment]
The clairvoyant killed the clown, and the clairvoyant died.

**Comment by SchokoShampoo** [comment]
so I fixed the problem, but you won't be able to see that he's in your team

**Comment by SchokoShampoo** [comment]
alf will fix this soon

**Comment by Alf21** [comment]
Should be fixed.
