### ISSUE TITLE
MAP minecraft_b5 ignite

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#108]
Есть такой баг, он связан с ТТТ, в обычной версии его исправили, у вас нет. Дело предстоит на карте minecraft_b5. Если вы попадаете в лаву и когда умираете, вы как наблюдатель можете все еще гореть и начав наблюдать за человеком, он будет получать урон от вашего огня и  в итоге умрет, это длится по времени как будто вы попали в лаву и вышли, такое же время. Я говорю про эту лаву, если вы попадете сюда:
![22223](https://user-images.githubusercontent.com/7480655/48918110-6325b000-eeac-11e8-92c3-f4fbc84a410c.png)

**Comment by Alf21** [comment]
Could you check whether it is fixed?
