### ISSUE TITLE
Weaponshop sync bug

### ISSUE THREAD

**Issue by Alf21** [Alf21/TTT2#11]
If the server is crashed or closed with [STRG] + [C] (I don't know why people does not use "exit"), the server is not able to sync the ConVars and gets async with clients ConVars. Initialize them as NetworkVars on server start-up.

**Comment by dok441** [comment]
Is it possible to disable this feature and write things as usual in TTT in the weapon files? So-as very often things are confused or added left things that should not be in this role. And also, if the server crashes, you have to go and choose to use your store to activate items from the role. I will be grateful if you tell me how to do it. The idea is good, which you offer, but in its current form, it only complicates the game.

**Comment by dok441** [comment]
Just noticed a bug, often the weapon circled in white, if the role selected, but it is not. And if you try to add or remove this weapon, it will always be circled in white.

**Comment by Alf21** [comment]
I’m sorry but I really don‘t understand what you want to say. Without these specific descriptions, i‘m not able to reproduce or fix anything :(

**Comment by dok441** [comment]
![12](https://user-images.githubusercontent.com/7480655/48085834-34a5a500-e21d-11e8-9e71-ad2472572465.png)
Here, I have not added the traitor, but it's highlighted if it is and it is constantly in this state, if you try to add or remove, it will always be selected, if it is added to the traitor shop. There is also a bug, the weapon is randomly added to the store, a traitor or a detective, etc. Even if you removed the weapon from the traitor, it can stay there and you need to click first for example to disable the inventory, and then again select enable to update all players and removed from the store is a weapon that you deleted. And still PR crash server, it is necessary to re-activate the weapons of the traitors, etc., but now do not have to choose a new one every time, just click "using own shop" and they are activated, but also can be added to the left weapon, which should not be in this role. Now you understand me?

**Comment by Alf21** [comment]
Im sorry, I understand your words but not the sense. I think this translator is terrible. Could you try to write in your language and i‘m using the translator. Just in case it could be better?

**Comment by dok441** [comment]
Вот я указал оружие, которое не добавлено у предателя, но оно выделено будто оно есть и оно постоянно в такой состоянии, если пытаешься добавить или удалить, оно всегда будет выделенным, будто оно добавлено предателю в магазин. Также есть баг, оружие случайным образом добавляется в магазин, предателя или детектива и тд. Еще если ты удалил оружие у предателя, оно может остаться там и тебе надо нажать с начало к примеру отключить инвентарь, а потом снова выбрать включить, чтоб обновилось у всех игроков и удалилось из магазина это оружие, которое ты удалил. И все еще при краши сервера, надо повторно активировать оружие у предателей и тд, только теперь не надо каждый раз выбирать новое, достаточна просто нажать "using own shop" и они активируются, но так же может добавится левые оружия, которые не должно быть у этой роли. Теперь вы поняли меня?

**Comment by Alf21** [comment]
Hmm... it‘s a bit better :) ty. This issue is commonly caused by doubled items / weapons. I will fix it by removing doubled items / weapons.

**Comment by Alf21** [comment]
Is it fixed?

**Comment by dok441** [comment]
Про отображения как активированных, вроде да.

**Comment by dok441** [comment]
Все еще после рестарта нужно тыкать повторно свой магазин, чтоб оружия активировались у роли.

**Comment by Alf21** [comment]
Hmm... it seems that your server crashed. If it is not the case, explain how you restarted your server please. :)

**Comment by dok441** [comment]
Я могу  exit выполнить в консоле сервера, могу перезапустить vds. Но все равно будет требовать снова нажимать на выбор "свой магазин", чтоб он загрузил все необходимые предметы для роли.

**Comment by dok441** [comment]
Yes
