### ISSUE TITLE
error vampire

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#110]
[ERROR] gamemodes/terrortown/entities/entities/vampire/shared.lua:274: attempt to index local 'color' (a nil value)
  1. fn - gamemodes/terrortown/entities/entities/vampire/shared.lua:274
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by Alf21** [comment]
When does it happen?

**Comment by dok441** [comment]
в начале раунда

**Comment by Alf21** [comment]
Then there has been another error before. This error can't happen without any reason.

**Comment by dok441** [comment]
[ERROR] gamemodes/terrortown/entities/entities/vampire/shared.lua:276: attempt to index local 'color' (a nil value)
  1. fn - gamemodes/terrortown/entities/entities/vampire/shared.lua:276
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

[ERROR] lua/includes/modules/draw.lua:182: attempt to index local 'color' (a nil value)
  1. RoundedBox - lua/includes/modules/draw.lua:182
   2. fn - gamemodes/terrortown/entities/entities/vampire/shared.lua:283
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by Alf21** [comment]
Yea i understand, but i can‘t reproduce. That‘s without any sense. Because this color ist requested after something, that ist created after the color. So it can‘t be „nil“, in no way

**Comment by dok441** [comment]
Это произошло, после недавних обновлений роли.

**Comment by Alf21** [comment]
Okay I will add a check to avoid this issue
