### ISSUE TITLE
The accomplice of a korefan, the traitor for the traitor.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#111]
Предателя превратили в сообщника шакала, но для своих предателей, он все еще отображался в табе и над игроком как предатель, я думаю это слишком хорошая идея и лучше, чтоб он убирался из предателей, чтоб не было таких внезапность и опасностей для тимкилла своего, при случайном уроне, подумав, что он сообщник шакала.
https://steamcommunity.com/sharedfiles/filedetails/?id=1572028148
https://steamcommunity.com/sharedfiles/filedetails/?id=1572029077

**Comment by Alf21** [comment]
Hmm so you think the traitors should be aware of their mates all the time? I‘m asking because if the Detective will be a Sidekick, it will still be displayed as Detective

**Comment by dok441** [comment]
No, on the contrary, that the detective, peresavat to be shown the detective if his jackal turned into the accomplice.

**Comment by Alf21** [comment]
Focused on this theme, I got many reports that it should be handled like it is at the current situation. I can‘t change it. But i could add a ConVar to toggle it...

**Comment by dok441** [comment]
Теперь я узнал фишку, шляпа дека упадет, если его превратили в сообщника.
