### ISSUE TITLE
HUD issue for Vampire and Hitman

### ISSUE THREAD

**Issue by Alf21** [Alf21/TTT2#113]
I‘ve received a bugreport that the TargetHUD and the BloodlustHUD is invisible after the last update. If it‘s true, I did a mistake the last 2 commits (in Hitman and Vampire) ago. There have been a change to support HUD modifications for those roles. I will check (and if it‘s true) fix it directly in the evening.

**Comment by Alf21** [comment]
Not again this color error o.O I really don‘t understand gmod and this HUD hook, every time there is a problem if I don‘t check everything that really don‘t need to be checked ... I will fix this in the evening finally..

**Comment by Alf21** [comment]
Okay should be fixed now :D

**Comment by Alf21** [comment]
But no error too xD
Please show me your modified version of this file. Maybe a link to pastebin or something like this. There is no reason why it shouldn’t work, so i think you modified the vampire role OR TTT2 (but it seems to be the vampire).

**Comment by dok441** [comment]
Все нормально, обновил vampire, видимо фиксы не все отображаются.

**Comment by Alf21** [comment]
Alright. By the way, I suggest sending commits with your Russian translations. This could improve TTT2 as well and in this way, you don't need to modify the new add-ons all the time and could be able to use the Workshop as well, if you want too.
