### ISSUE TITLE
New Role: Priest

### ISSUE THREAD

**Issue by h4ppy1337** [Alf21/TTT2#118]
The Priest can help the innocents to win the game with God's power. However, he needs to think about his decisions beforehand, for every wrong step could be his last.

- The Priest starts the game with a unique weapon, the Holy Deagle. It has the same model like the normal Deagle, so noone can identify it while being carried. The Holy Deagle is undroppable and has a maximum amount of 1 bullet. When empty, the Holy Deagle refills every 60 seconds.

- The Priest can convert every innocent team member to join his brotherhood by shooting them with the Holy Deagle. Players who get converted keep their roles, meaning that innocents with special roles still have their special abilities when being in brotherhood. While in brotherhood, every member can see who is in brotherhood already by pressing tab. 

- However, the Detectives have always been heathens, as they will not be able to join the brotherhood. When the Priest shoots any detective with the Holy Deagle, it deals 30HP damage to the Detective

- When the Priest shoots any Traitor, Jackal or Serialkiller with the Holy Deagle, the Priest dies.

- When the Priest shoots the Jester with the Holy Deagle, the Jester dies and the game continues. The Priest also kills any Sidekick when he shoots him with the Holy Deagle, as the sidekick's power is not yet strong enough to beat the power of God.

- When the Priest shoots the Unknown player with the Holy Deagle, he becomes a normal member of the brotherhood. The unknown player keeps his status as a brother even after dying the first time, meaning that the Unknown is the only player being able to be a member of the brotherhood and still having a negative role.

- When the Priest shoots any Infected player with the Holy Deagle, the Infected player dies. On the downside, if the Priest gets infected by any player, the whole brotherhood immediately gets infected too.

**Comment by iViscosity** [comment]
I'm a bit confused about the implementation of this role...

> When the Priest shoots any Traitor, Jackal or Serialkiller with the Holy Deagle, he dies.
Who dies? The Priest or the T/J/SK?

> When the Priest shoots the Unknown player with the Holy Deagle, he becomes a normal member of the brotherhood.
Same question here.

> The unknown player keeps his status as a brother even after dying the first time
I'm guessing this is a feature with the Unknown role? Where do I learn more about this

**Comment by h4ppy1337** [comment]
Hey, thanks for your interest.

Of course, the Priest dies when trying to convert any Traitor/Jackal/SK, because in first place noone evil is supposed to join the brotherhood (exception here is the Unknown who might be able to be reborn as a negative role), and also in second place to nerf the Priest. 
If the Priest was able to kill every negative role in the game and in addition to that also build an army of innocents knowing each other's Innocence that'd be pretty much broken. He already is able to kill 3 more or less bad guys with his deagle (Infected, Sidekick, Jester), so he obviously needs to get some balance. 
This happens by implementing that the Priest dies when trying to shoot any T/J/SK and by the fact that, if the Priest gets infected, any member of the brotherhood also gets infectet. This also slightly boosts the Infected, as for in my opinion they are the weakest negative party.

The other two questions of yours are pretty much answered by the above as well, as the Unknown player  **can** be converted while still being an Unknown, but **cannot** be converted anymore when being reborn as a T/J/SK. However, if he has been converted beforehand (or if he is reborn as an innocent) he of course is able to stay (become) a member of the brotherhood.

**Comment by h4ppy1337** [comment]
No, the idea of this role is to create a possibility for the innocents to be able to build fractions, when the Priest is played properly. When saying Innocents can be converted, I'm speaking of all of them, i.e. the whole team "Innocent". This includes any special role which is assigned to the Innocent team, e.g. Clairvoyant, Survivalist and possible other roles to be implemented. 
As for the Detective, in my concept, it would be too easy to be able to convert him, as he would always be a free teammate, so I made him the only Innocent team member being unable to join the brotherhood. 
Nonetheless, the idea of the Brotherhood is being a "secondary special role", if you want so. Not that it has to be shown anywhere as such, but just so that it does **not** overwrite the current Innocent's special role. The only impact the Brotherhood status has on the game is the power to see every member by having a look at the player's list (TAB), if you yourself are a member. Any possible special roles of people who get converted into the Brotherhood should not be overwritten.

**Comment by iViscosity** [comment]
Okay. That is sort of how I was doing this. Basically, the best way is to check for the Team. If they're apart of TEAM_INNOCENT, they can be converted to TEAM_BROTHERHOOD.

That's my understanding, at least. Does Team Innocent win with Team Brotherhood? From how you described the Detective, I think it does. Basically, the Priest just acts as a glorified Innocent tester, it seems.

**Comment by h4ppy1337** [comment]
I hope you mean "a part" rather than "apart" :D then I would agree with you. Team Brotherhood obviously is working together with team Innocents, as team Brotherhood practically is a subteam of team Innocent, and therefore of course wins with it. 

The Priest acts as a glorified Innocent tester in some way, he even has the ability to kill some roles (as seen above) but also has the big downside of dying when trying to convert a T/J/SK. Also, there is the debuff with when being Infected, all members get Infected as well, to balance him and also slightly buff the Infected.

This makes him a strong role when played properly, but the waiting time of 60 seconds after every Holy Deagle shot balances him to not being able to snatch the whole game. Also, he needs a bit of luck, as every shot, especially in early game, could be his last.

**Comment by iViscosity** [comment]
Yes, I did mean "a part". My phone has a tendency to change everything I mean. The best way I can think of doing this is just doing a custom round win checking and pairing Brotherhood with Innocent, and treating them as an Innocent win (as opposed to having a Brotherhood Win type).

**Comment by iViscosity** [comment]
First commit uploaded: iViscosity/ttt2-role_priest@37fbe9603ab217044e245ceba2dad42c87787fc0

**Comment by h4ppy1337** [comment]
Nice work, and very well done! I see you mentioned you don't know German, as I am a native German I could give you some text fragments if you tell me what's needed.

**Comment by iViscosity** [comment]
Ah, I just put that there because every role Alf makes has a Deutsch translation :)

**Comment by h4ppy1337** [comment]
I see. Given he's German as well, I guess he'd implement it by himself then. But if not, or in case you want to improve the code, you can hit me up anytime. 
How do I test these? Do I just need to add them manually?

**Comment by Alf21** [comment]
@iViscosity nice work! Well chosen hooks :)
@h4ppy1337 yea just put it into your "addons" folder on the server :)

**Comment by iViscosity** [comment]
Another update.

https://github.com/iViscosity/ttt2-role_priest/commit/bfabb8e7d901d6e93b11b667a54a669e6c58ba03

**Comment by h4ppy1337** [comment]
Very nice! Can't wait to test it out later. Again, thanks for your interest and effort, i appreciate it a lot and am looking forward to it becoming an actual addon :)

**Comment by iViscosity** [comment]
I'd recommend not testing it on a live server, because there could and probably are some bugs. If you have an offline or private server, I would test it on there, first :)

And you can use [my issues page](https://github.com/iViscosity/ttt2-role_priest/issues) for any errors you do find.

**Comment by iViscosity** [comment]
@Alf21 I need some help with the Deagle for this.

The code I used for detecting when a player is hit is the same as the SK's knife. I was worried this would mimic the knife's range and it turns out that's the case. Currently it's like this

```lua
local spos = self:GetOwner():GetShootPos()
local sdest = spos + (self:GetOwner():GetAimVector() * 70)
```

What would be a good value to increase it's range? If you're not sure (like just trial and error), I'm thinking of just using an [PlayerShouldTakeDamage hook](http://wiki.garrysmod.com/page/GM/PlayerShouldTakeDamage) and do checks there.

**Comment by Alf21** [comment]
The best and easiest way is to just copy and modify the target detection in my golden deagle repo :)

**Comment by Alf21** [comment]
This still alive?

**Comment by h4ppy1337** [comment]
For me, of course. But I haven't heard from iViscosity in a while. Don't think he's still working on it, sadly. And since I don't know Lua, I can't continue alone either.

**Comment by iViscosity** [comment]
I'd like to still work on it, but work and school have been really busy and I don't have a ton of free time. I'll start work on it again, might start from scratch if I want to do it in a different way, but we'll see.

Also, not gonna lie, completely forgot about this.

@Alf21 what exactly do you mean by "copy and modify the target detection in my golden deagle", what would I modify?

**Comment by Alf21** [comment]
You could use the sidekick deagle 1 to 1. you just need to replace the Sidekick functions

**Comment by iViscosity** [comment]
@Alf21 I see you made some changes to how roles are added, etc.

Was checking your Sidekick repo and see stuff like `roles.InitCustomTeam` etc.

Do you have any updated documentation so I don't have to try to figure it out myself? :P

**Comment by TimGoll** [comment]
Right now there is no documentation. We plan on writing one.
But feel free to figure it out by yourself and ask on discord for help. Onece you understood how to do it, you can use your knowledge and help us writing a documentation

**Comment by iViscosity** [comment]
Will do. Just realized my fork was out of date so once everything updated I'll start figuring it out :)

**Comment by Alf21** [comment]
Yea we improved and simplified the system

**Comment by TimGoll** [comment]
@iViscosity Just checked your work on this role and it's really good. Please ping me once you need a role icon or some other role specific graphics. I'd like to help with this role :)

**Comment by TimGoll** [comment]
So I checked this one here again and while I like it, I have on question: Is there a way for the priest to win? And is he a part of the innocent team?

I might implement this role in the next few days, since @iViscosity seems to be uninterested in implementing this role and I've added a new status system https://github.com/Alf21/TTT2/pull/338 which would work nicely with this since. At least how I undestood the role :D

**Comment by h4ppy1337** [comment]
@TimGoll I would be delighted if you'd be implementing this one :)

The priest is part of the innocent team, therefore he wins alongside with them under the known conditions. His special role simply allows him, while the game is progressing, to form a small group of people who are able to trust each other (except when one of the Brothers gets sidekicked), because only innocents can become Brothers (or Monk, call them whatever you like). 

But as every role has its downside, the Priest can't just Holy Deagle every person he sees and hope for success, as he has a cooldown in his actions. Additionally, he might risk his life because he dies when shooting a bad guy (exceptions from that as well as possible scenarios are stated in the original post)

**Comment by TimGoll** [comment]
Okay, thank you. I do not have that mich time in the next two weeks, but I'll keep it in the back of my head

**Comment by TimGoll** [comment]
Implemented and available at: https://github.com/TTT-2/ttt2-role_pri
