### ISSUE TITLE
Protection against murder of a jackal by the accomplice

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#122]
У меня установлена защита на ttt2_siki_protection_time 60 но она не работает, в итоге сообщник может убить тут же шакала, когда он его превратил. Она точно нормально работает?

**Comment by dok441** [comment]
Только что проверил, не работает.

**Comment by SchokoShampoo** [comment]
Should be fixed

**Comment by dok441** [comment]
fix yes
