### ISSUE TITLE
Improvement of a karma

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#123]
Очень часто, много людей, заходят ради рдма и выходят. Я думаю можно внести данное дополнение, чтоб если в тебя невиновный стреляет и наносит к примеру 20 урона и ты его убьешь, тебе не снимут карму. Или допустим, невиновный, убил невиновного и другой невиновный убьет его за это, то убийце не снимут карму, при учете, если 1 правила, не работало.
С уроном, есть уже дополнение, его можно будет просто импортировать https://steamcommunity.com/sharedfiles/filedetails/?id=1441066191&searchtext=ttt_improved_

**Comment by Alf21** [comment]
Nice solution. I will keep in it mind while implementing this.
