### ISSUE TITLE
jester bug to pomegranate

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#124]
Как мы можем увидеть, по какой-то причине я смог взять гранату, видимо до определения  ролей и за шута смог её выкинуть, что может навредить другим игрокам
![555](https://user-images.githubusercontent.com/7480655/49089024-6fc75100-f27c-11e8-94c2-b667a1cd4c03.png)

**Comment by dok441** [comment]
Так же все еще шут может скинуть людей ломом, раз вы пофиксили, что он не может взять прпопы, я думаю, надо убрать возможность толкать ломом, так-как часто люди сталкивают, что приводит к ненужным нарушениям.

**Comment by SchokoShampoo** [comment]
> Так же все еще шут может скинуть людей ломом, раз вы пофиксили, что он не может взять прпопы, я думаю, надо убрать возможность толкать ломом, так-как часто люди сталкивают, что приводит к ненужным нарушениям.

I will fix this with a ConVar so you can toogle this by yourself
