### ISSUE TITLE
jester no respawn 

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#127]
Как мы видим на скриншоте, шута убил вампир, но когда вампир умер, шут остался все еще мертвым, так и не возродившись.
![66666](https://user-images.githubusercontent.com/7480655/49095964-5c6fb200-f28b-11e8-8e43-1bc7b35f2eae.png)

**Comment by dok441** [comment]
Система так баганулась, что вместо шута, возродился человек, у которого был слей и ему далась роль вампира. Он при слеи был невиновным.

**Comment by SchokoShampoo** [comment]
I can't recreate this error.
which of the 5 winstates were enabled?

**Comment by dok441** [comment]
По стандарту, все 5, как я понимаю.

**Comment by SchokoShampoo** [comment]
Someone else was revived, after the killer died, with the role of the killer?

**Comment by dok441** [comment]
Только другой человек, у которого был слей выдан через damagelogs, все остальные если были мертвы, так и остались мертвы.

**Comment by SchokoShampoo** [comment]
Thats wierd :/
This shouldn't be possible

**Comment by SchokoShampoo** [comment]
how often did this happen?

**Comment by SchokoShampoo** [comment]
Since which update version does this error occour

**Comment by dok441** [comment]
Прошлого.

**Comment by SchokoShampoo** [comment]
does the error still occour?
