### ISSUE TITLE
New Icon Set

### ISSUE THREAD

**Issue by Alf21** [Alf21/TTT2#128]
@Mineotopia aka @TimGoll created some new Icons and rematched / adjusted some colors to connect each role with it‘s base role easier. Here we go: https://cdn.discordapp.com/attachments/495532865191411714/515882248566865920/unknown.png

The Link and text to the author focused on this topic: "I tweaked the colours of the roles, even the default traitor, inno and dete colours. Mostly subtle, some are vastly different. What do you think about it?
full res: https://github.com/TimGoll/steam_icons/tree/master/TTT2"

**Comment by h4ppy1337** [comment]
Nice work there. The use of letters bothered me anyway, since letters are limited and some roles already start with the same letter. With some new additional roles probably yet to come, this is the best solution to prevent possible icon problems

**Comment by TimGoll** [comment]
@h4ppy1337
If you have some ideas zo improve the icons further, please let me know.

**Comment by dok441** [comment]
good job

**Comment by Alf21** [comment]
done with #134
