### ISSUE TITLE
rolesetup, role count

### ISSUE THREAD

**Issue by TheSuspect2306** [Alf21/TTT2#132]
There are 2 traitors, 5 innocents and 0 spectators this round.
Wir waren zu dem zeitpunkt 9 spieler
rollen: jackal, sidekick, hitman, undertaker, infected

**Comment by SchokoShampoo** [comment]
Es werden nur Team Traitor und Team Inno gezählt

**Comment by TheSuspect2306** [comment]
achso ich dachte alle nicht traitor zählen als innocent dachte es wäre ein bug

**Comment by SchokoShampoo** [comment]
Wir haben drei Alternativen:
1. Wir können die anderen Rollen zu Innocents zählen
1. Wir können die anderen Rollen extra aufzählen
1. oder wir können sie weglassen

wir hatten uns für die dritte möglichkeit entschieden, da man so zumindestens weiß, dass weitere Rollen dabei sind wenn man aufpasst, aber nicht unbedingt welche

**Comment by SchokoShampoo** [comment]
Wir können da gerne nochmal drüber diskutieren, falls du eine andere Antwort als sinnvoller erachtest

**Comment by Alf21** [comment]
Der Jackal wird btw. zu den Innocents gezählt

**Comment by TimGoll** [comment]
grundsätzlich finde ich Alternative 3 sinnvoll, man sollte aber konsistent sein
abgesehen davon finde ich, man sollte das gar nicht anzeigen und sich überraschen lassen, oder sowas wie "there are two traitors and one detective this round", ohne die Angabe der Innoanzahl

**Comment by SchokoShampoo** [comment]
Man kann mittlerweile über ulx diese nachricht sowieso deaktivieren ^^

**Comment by SchokoShampoo** [comment]
ne die diskussion ist da irgendwie eingeschlafen
mache evtl mal demnächste ne umfrage wenn bei mir die klausuren rum sind

**Comment by SchokoShampoo** [comment]
Hat da irgendjemand spezielle Wünsche?

**Comment by TimGoll** [comment]
Ist das nicht inzwischen geklärt? Ich schließe das mal, wenn jemand das Bedürfnis hat dazu noch was zu sagen, dann kann es ja wieder geöffnet werden.
