### ISSUE TITLE
ttt spectator deathmatch round time +30 seconds for a death in specdm

### ISSUE THREAD

**Issue by TheSuspect2306** [Alf21/TTT2#133]
wenn jemand stirbt im specdm wird ca 30 sekunden zeit geadded

**Comment by SchokoShampoo** [comment]
Bug ist gefixt kann aber specDM noch nicht pushen bis Alf mir das Freischaltet ^^

**Comment by SchokoShampoo** [comment]
In Github sind die Fixes jetzt drin, workshop kommt später

**Comment by SchokoShampoo** [comment]
Nach erneuten Tests funktioniert es jetzt endgültig
