### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#135]
Я хотел бы сделать русский перевод этого режима. В каком виде мне его предоставить?

**Comment by SchokoShampoo** [comment]
Alf and I already talked about asking you for a russian translation ^^
So I just created a Template (can also be used as translation addon for TTT2 + all Roles +  Rolesetup) to fill in.
Have a look: https://github.com/TTT-2/ttt2-translation

**Comment by SchokoShampoo** [comment]
Also the most Strings could be copied from your own gmod installation:
GarrysMod/garrysmod/gamemodes/terrortown/gamemode/lang/
in your example russian.lua

**Comment by dok441** [comment]
Запрос на перевод добавлен.

**Comment by Alf21** [comment]
@SchokoShampoo

**Comment by Alf21** [comment]
Okay russian translation included for TTT2. The translation for the custom roles needs to get added externally (as an add-on)
