### ISSUE TITLE
There is no loss from falling

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#136]
При падении нету урона.

**Comment by dok441** [comment]
![33333](https://user-images.githubusercontent.com/7480655/49217775-58a97000-f3f0-11e8-8df6-c09ebc06d894.png)

**Comment by dok441** [comment]
До начала раунда, ты можешь попасть туда, где ты по идеи должен умереть и после начала ты там можешь находится.

**Comment by dok441** [comment]
Так же в ловушка Т, люди не гибнут. Видимо это снова из-за шута, как раньше. Что-то не так с обновлением шута видимо.

**Comment by dok441** [comment]
Удалил шута и сразу все стало нормально, явно дело в нем.

**Comment by SchokoShampoo** [comment]
can you check again there was an error in the jester
