### ISSUE TITLE
Too bright color of a role

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#137]
![353535](https://user-images.githubusercontent.com/7480655/49222954-32d79780-f3ff-11e8-8954-5855869431c7.png)
Как мы можем увидеть, цвет роли в табе слишком желтый, что режит глаза и мешает прочитать ник игрока.

**Comment by Alf21** [comment]
@TimGoll

**Comment by TimGoll** [comment]
I wasn't sure by myself if this yellow was the best choice. Tanks for the report, I'll change it.

**Comment by Alf21** [comment]
@TimGoll  Did you change it? :)

**Comment by TimGoll** [comment]
Actually, no. But I can change it right now.

**Comment by TimGoll** [comment]
What about `94,76,118`?

![image](https://user-images.githubusercontent.com/13639408/49450842-29bf3f80-f7de-11e8-9630-f47d502f5c89.png)

**Comment by Alf21** [comment]
Hmm do you think this color associates with the Inno team?

**Comment by TimGoll** [comment]
because of the traitor colour? I don't think so.
But to be fair, I had no better idea while trying different colours
