### ISSUE TITLE
random server crash on role giving ??

### ISSUE THREAD

**Issue by TheSuspect2306** [Alf21/TTT2#140]
bin ich der einzige der das problem hat das seit update 2.6.0 das der server bei rollenverteilung random crasht ?

**Comment by dok441** [comment]
Замечу, что есть краш, но без перезапуска сервера, а когда сервер использует 100% ядро вашего процессора и сам не перезапускается, возможно это связано с выше описанной проблемой, а возможно с рэгдоллами трупов, так-как они все еще летают.

**Comment by TheNickSkater** [comment]
Hatte bis jetzt nur 1 Crash, und der ist am sofort am Ende der letzten Runde passiert. Also genau wenn der Mapvote starten sollte. Der Server hat dann bei mir einfach nicht mehr reagiert, alle Spieler sind ausgetimed und auch die Console konnte keine Commands mehr ausführen.

**Comment by SchokoShampoo** [comment]
Wir hatten zwischenzeitlich mal im Jester den Bug, dass der Server sich in einer Endloschleife aufgehängt hat, wenn der Jester getötet wurde, wodurch alle Spieler ausgetimed sind und der Server nicht mehr reagiert hatte. In einer Version kam es glaub ich auch am Rundenende zu einer Endlosschleife, aber aktuell sollte es keine Probleme diesbezüglich geben

**Comment by Alf21** [comment]
Beide genannten Crashes lassen sich im Ablauf allerdings nicht in einen dieser uns bekannten alten Bugs einordnen. @TheSuspect2306 vielleicht mal schauen, an welchem Add-on es liegt? (Falls Du es finden solltest, bitte bescheid sagen, wie es heißt).

**Comment by dok441** [comment]
На счет краша когда выпадают роли, это правда, сейчас у меня сервер крашнулся при начала раунда, только написало какие роли и сервер упал. Человек на сервере было 16. Последние что было написано, это "Есть 4 предател(ь/ей), 10 невиновн(ых/ый) и 0 наблюдател(ь/ей) в этом раунде."

**Comment by dok441** [comment]
[core.zip](https://github.com/Alf21/TTT2/files/2637123/core.zip)
Вот dump

**Comment by Alf21** [comment]
> [core.zip](https://github.com/Alf21/TTT2/files/2637123/core.zip)
> Вот dump

What is this file? There isn't any file extension. I'm not able to open it, it does not have any minidump or dump file extension or structure...

**Comment by Alf21** [comment]
![20181202201032_1](https://user-images.githubusercontent.com/11843790/49343691-a4694d00-f66e-11e8-80ce-967e0c488048.jpg)
![20181202200945_1](https://user-images.githubusercontent.com/11843790/49343692-a4694d00-f66e-11e8-8c0b-477e3d757dcc.jpg)

I'm playing with more than 16 Bots and doesn't got this bug...

**Comment by dok441** [comment]
Это происходит рандомно. По какой причине я не знаю, но человек утверждал, что у него тоже есть, означает 2 совпадения, не думаю, что это случайность.

**Comment by TheNickSkater** [comment]
Ist mir jetzt aber auch schon 1-2 mal passiert.. Bei der Rollenverteilung einfach so gecrashed.. ohne Fehler oder sonstwas.

**Comment by TheSuspect2306** [comment]
Es ist passiert bei Maps wie zb waterworld remastered bei minecraft b5 xn oder redux crasht es nicht

**Comment by Alf21** [comment]
![20181203204234_1](https://user-images.githubusercontent.com/11843790/49397601-5a4e9d00-f73c-11e8-91cc-9b7384c847cb.jpg)
Nein, tut es nicht.

**Comment by TheSuspect2306** [comment]
Es kann vllt schon gefixt sein nach den ttt2 Update wo du die getrole und so geändert hast bis dahin haben wir nix getestet weil kaum jemand da war

**Comment by dok441** [comment]
Сегодня был краш, он не связан с ролями, но я полагаю с трупами. Я собрал всю нужную информацию для вас. 
[crash.zip](https://github.com/Alf21/TTT2/files/2644780/crash.zip)

**Comment by Alf21** [comment]
You can find crashlogs in your game folder. ( Usually Steam/steamapps/common/GarrysMod/ ) They end with ".mdmp". These contain information we can use to work out why you have crashed.

Source: https://wiki.garrysmod.com/page/Crash_Reporting

Does it depends on the map? On the amount of players? On TTT2 itself? By a specific TTT2 role? These informations are important :)
I hope you understand this, because i‘m not able to Donnerstag anything without it. A crash without an error is the worst thing that could happen to developers...

**Comment by dok441** [comment]
Это у клиента, а у сервера создается файл core, который я предоставил.

**Comment by Alf21** [comment]
So the server is crashing, but not the client, is it right?
If so, how long does it take until the server crashes and how many players are on this server. It‘s important to know this to be able to reconstruct the problem that is causing this crash (maybe)...

**Comment by dok441** [comment]
Да, именно сервер. Памяти свободной еще много.

**Comment by Alf21** [comment]
Okay, how many rounds you played on the map WITHOUT mapchange?

**Comment by dok441** [comment]
Вот сейчас это снова произошло на 6 раунде из 11. Происходит часто в начале раунда.  Бывало в первом же раунде на карте, раза 2 такое сам наблюдал.
Последнее, что было на стороне клиента:
You are: INNOCENT
[TTT2]:	Предатели выбраны.
Round state: 3
[TTT2]:	Раунд начался!
Есть 3 предател(ь/ей), 12 невиновн(ых/ый) и 2 наблюдател(ь/ей) в этом раунде.
ZUBOHISTKA has been autoslain by Shiro 2 minutes ago with the reason: 'RDM'.

**Comment by Alf21** [comment]
You say it happens in round 6 of 11, but in the other sentence, that it happens in the first round of a map. What do you mean especially? It‘s hard because i‘m not able to reconstruct it, i don‘t have this issue with my low performance test server

**Comment by dok441** [comment]
Означает это происходит не из-за раунда, а из-за чего-то другого. Вот к примеру как мы видим сейчас, у человека слей был и начался раунд, возможно тогда у людей был слей или это из-за начала раунда. Как мы видим, в консоле сервера интересное сообщение: 
Engine error: area(1==16843008, 2==11) >= numareas (17): Check if engine->ResetPVS() was called from ClientSetupVisibility 
Я не могу сам узнать какая причина, начало раунда очень часто было и в этот момент крашился сервер. Часто это связано с убийством, как мы видим, здесь слей, в других случаях, там убивают в конце человека, возможно проблема с рэгдоллами и они как-то ломают сервер.

**Comment by Alf21** [comment]
Seems to be caused by the map: https://forum.facepunch.com/f/gmoddev/mhzc/Getting-disconnected-with-really-weird-errors-srcds-crashing-like-it-s-2008/1/

**Comment by Alf21** [comment]
It must be caused by the translator, but that's the same as here. A crash is a crash, not a shutdown. There, this guy has a crash too.

**Comment by dok441** [comment]
L 12/09/2018 - 18:49:48: Engine error: models/props_junk/plasticcrate01a.mdl (2) at -22.0 -1.5 -33.1 in contact with player/guerilla.mdl (2) at nan nan nan, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000
Был краш, вот написало в конце.

**Comment by dok441** [comment]
Насколько я знаю, лучшая версия против краша https://github.com/mcNuggets1/mg_ttt_anticrash Но при ней тоже бывают краши.

**Comment by dok441** [comment]
Так же знаю версию против краша https://github.com/mcNuggets1/mg_ttt_anticrash/blob/master/lua/autorun/sh_ttt_anticrash.lua

**Comment by Alf21** [comment]
I reworked the selection system, this should fix very rare endless loops and crashes

**Comment by dok441** [comment]
Переработанная система вроде помогает. Пока не 1 краша не было.
