### ISSUE TITLE
InitCustomRole funktioniert nicht

### ISSUE THREAD

**Issue by tintinmaster** [Alf21/TTT2#143]
Ich versuche 2 weitere Rollen zu meinem Server hinzuzufügen, Ich habe 2 identische Dateien, einziger Unterschied ist der Name der Rolle und die Übersetzungen. 
Das Problem ist, dass nur eine der beiden Rollen erkannt wird und im Spiel verfügbar sind

**Comment by Alf21** [comment]
Das ist eben wie Lua in GMod arbeitet. Dateien mit gleichem Namen und gleichem Pfad überschreiben sich. Einfach eine Datei oder den Pfad umbenennnen?

**Comment by tintinmaster** [comment]
Ich hab 2 Files shared.lua die sind jeweils in 2 verschieden Ordnern für 2 verschiedene Rollen.
https://gitlab.com/tintinmaster/ttt2_jan/blob/93875f61d457d598fe32ce8e2f0adbdefc984b62/lua/entities/shared.lua 
https://gitlab.com/tintinmaster/ttt2_tim/blob/4b15b04361a8b45d4e61d0b50a444a97441eed28/lua/entities/shared.lua

**Comment by tintinmaster** [comment]
Oder muss ich die trotzdem umbenennen, obwohl die in verschiedenen ordner, sozusagen also in verschiedenen addons sind?

**Comment by SchokoShampoo** [comment]
Der schreibt sozusagen alle addons zusammen in das game verzeichnis. Deswegen überschreibt die init.lua von alf ja auch die init.lua vom normalen ttt

**Comment by Alf21** [comment]
Für einfache Lua Programmierung empfehle ich Lua Tutorials.
Ansonsten bezogen auf TTT2 hast du ein paar Fehler bei dem Unterscheiden zwischen TEAM_JAN und ROLE_JAN. Wenn du ersetzt, dann aber richtig.
Das Problem sollte gelöst werden, wenn du die shared.lua files einfach in nen Ordner mit dem Rollennamen packst, also zB jan.

**Comment by tintinmaster** [comment]
Hab jetzt die Files umgenannt, funktioniert jetzt alles, dachte es reicht, wenn die in verschiedenen Ordnern liegen, die unterschiedlich heißen

**Comment by Alf21** [comment]
Tut es auch, aber erst ab dem Lua/ Ordner zählend
