### ISSUE TITLE
Useless detective story.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#145]
У детектива есть бинокль, если мы делаем, чтоб подтверждать смерть нужно нажимать кнопку, бинокль не будет подтверждать смерть, что в принципе ломает оружие.

**Comment by Alf21** [comment]
maybe you don't have activated "ttt_identify_body_woconfirm"? If so, I will fix the bug that the body doesn't confirm on clicking confirm. It's a TTT bug...
