### ISSUE TITLE
Shutdown of the choice of a role.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#146]
https://media.discordapp.net/attachments/345978661490393088/518753698722349057/unknown.png
Есть настройка на отключение роли, но она не работает, человек убрал становление hitman, но все равно стал ей.

**Comment by Alf21** [comment]
This option doesn't mean that you won't be a Hitman. It just means that if you don't want too, other traitors will be the Hitman. But if there are no other NORMAL (!) Traitors anymore, you will be Hitman.
