### ISSUE TITLE
The clown who could...

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#147]
Произошел баг с шутом, шут в начале раунда мог наносить урон, если верить логам.  После шут не возродился.
![332232](https://user-images.githubusercontent.com/7480655/49339700-66146380-f657-11e8-915c-6c468c4ad41a.png)

**Comment by SchokoShampoo** [comment]
did you asked Giancho if he really was the jester, maybe he was forced to another role like sidekick or something

**Comment by SchokoShampoo** [comment]
problem is still #58

**Comment by SchokoShampoo** [comment]
I cant damage anyone as a jester!!! do you have the newes version of ttt2 and the jester?

**Comment by dok441** [comment]
Да есть.

**Comment by SchokoShampoo** [comment]
The logs reports the damage that would be dealt if it wasn't the jester

**Comment by SchokoShampoo** [comment]
should be fixed

**Comment by dok441** [comment]
Не исправлено.

**Comment by SchokoShampoo** [comment]
Forgot to push yesterday please try again
