### ISSUE TITLE
ttt_identify_body_woconfirm 0 not working

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#148]
ttt_identify_body_woconfirm 0 не подтверждает трупы.

**Comment by Alf21** [comment]
That's the sense of ttt_identify_body_woconfirm "0". To identify a body, you need to click on "confirm" manually. ;)

**Comment by dok441** [comment]
После вашего последнего сегодня обновление, тела перестали вообще при нажатии подтверждаться, я про это говорю.

**Comment by Alf21** [comment]
if you turn it to 0, you need to press on "confirm" in the dialogue. If you turn it to 1, the body will automatically confirm on searching it.

**Comment by dok441** [comment]
Я это знаю и где надо подтверждать тело, при обновлении не работает нажатие, оно не подтверждает просто тело.
