### ISSUE TITLE
Translation change, for normal work.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#149]
L.traitor = "Traitor" надо менять на L.traitors = "Traitor" иначе он не будет видеть перевод, я уже под себя многое изменил, но такая проблема есть, в вашем же переводе многое без приписки s в конце.
Это после последнего обновления как раз появилось, либо я просто включил опцию ttt2_confirm_team 1

**Comment by SchokoShampoo** [comment]
actually there is already a L.traitors = "TEAM Traitor"
