### ISSUE TITLE
TTTPlayerSpeedModifier Hook

### ISSUE THREAD

**Issue by svenom** [Alf21/TTT2#15]
**Describe the bug**
"TTTPlayerSpeedModifier" Hook dont work correctly
Gmod Changes the Hook for Player speed. Now in the shared.lua 
Weapons like Homerun Bat wont give movement speed

**To Reproduce**
Equip a Homerunbat 

**Expected behaviour**
25% more Movement Speed

**Additional context**
see In the player_ext.lua the plymeta:SetSpeed function

**Comment by Alf21** [comment]
Thanks! Should be fixed with the last update 0.2.5b
