### ISSUE TITLE
The clown became a clown again.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#151]
Иногда происходит баг с шутом, он возрождается после смерти, снова с ролью шута. Урон так же не может наносить. Логи показывают все еще, что он будто наносит, но это прошлый тикет, он все еще не исправлен.
![3333344](https://user-images.githubusercontent.com/7480655/49457636-f8119d00-f80c-11e8-8176-b05c70bf8546.png)
![444](https://user-images.githubusercontent.com/7480655/49457700-1aa3b600-f80d-11e8-9803-8de07ae4a596.png)

Используется последние обновление шута.

**Comment by SchokoShampoo** [comment]
Did this happen just once or more often?

**Comment by SchokoShampoo** [comment]
Please Test ^^

**Comment by SchokoShampoo** [comment]
Could you please check if fixed?
