### ISSUE TITLE
The end or it only the beginning?

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#153]
На данном ролике видно, что конец раунда происходит неадекватно, то есть, он есть, но нет в чате, надписи кто кем был и нет финального меню, просто раунд окончен при убийстве, произошло это случайно, помог перезапуск карты.
https://www.youtube.com/watch?v=IxGJK94qTIg

**Comment by Alf21** [comment]
That's really weird, but I think that it's caused by a server async state (server lag) OR another add-on. Never experienced this :o

**Comment by Alf21** [comment]
Anything new about this issue?

**Comment by dok441** [comment]
Больше её не было.
