### ISSUE TITLE
specdm error

### ISSUE THREAD

**Issue by TheSuspect2306** [Alf21/TTT2#156]
[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

[ttt2] addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241: attempt to call method 'IsGhost' (a nil value)
  1. Call - addons/server_tool_specdm/lua/sv_specdm_overrides.lua:241
   2. unknown - gamemodes/terrortown/gamemode/player_main.lua:749

Timer Failed! [Simple][@gamemodes/terrortown/gamemode/player_main.lua (line 746)]

hab eig die neuste specdm UND ttt2 version also die 7.1 ttt2
kommt immer bei prepairing

**Comment by Alf21** [comment]
Alright, was a bug. Ty, fixed
