### ISSUE TITLE
At first innocent, and then HITMAN

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#157]
В один момент, человек становится противоположной ролью, он был невиновным изначально. Связано я полагаю это с ролью шут.
Убил он только вампира за этот раунд, до превращения в HITMAN
![2223](https://user-images.githubusercontent.com/7480655/49688558-eb0aeb80-fb35-11e8-913f-2e7c566e2c78.png)

**Comment by Alf21** [comment]
That‘s damagelogs ...

**Comment by dok441** [comment]
Игрок сам говорит, он был инно, как в друг становится хитманом, я описывал не так давно баг с шутом, где человек так же стал ролью другой, вместо шута, как я понимаю, история повторяется.

**Comment by SchokoShampoo** [comment]
So you have random role-changes at different situations?

**Comment by dok441** [comment]
Да, я полагаю это связано с шутом. Происходит какой-то баг.

**Comment by SchokoShampoo** [comment]
Did you try for sometime without the jester

**Comment by dok441** [comment]
I deleted the clown and it was not. But I cannot tell on long prospect.

**Comment by SchokoShampoo** [comment]
i will check this.

**Comment by SchokoShampoo** [comment]
Please Test ^^

**Comment by SchokoShampoo** [comment]
Could you please check if fixed?
