### ISSUE TITLE
ERROR CLIENT

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#159]
[ERROR] addons/animations/lua/autorun/client/ttttargetclienthit.lua:54: attempt to call method 'IsActive' (a nil value)
  1. func - addons/animations/lua/autorun/client/ttttargetclienthit.lua:54
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by dok441** [comment]
Server error 
[ERROR] addons/animations/lua/autorun/server/tttchatpeople.lua:101: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. fn - addons/animations/lua/autorun/server/tttchatpeople.lua:101
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:109
     4. EndRound - gamemodes/terrortown/gamemode/init.lua:933
      5. unknown - gamemodes/terrortown/gamemode/init.lua:432

**Comment by Alf21** [comment]
Yea as I thought, this is caused by another add-on

**Comment by dok441** [comment]
У меня кроме оружия никаких дополнений нет, о чем вы?

**Comment by dok441** [comment]
[ERROR] addons/animations/lua/autorun/client/ttttargetclienthit.lua:54: attempt to call method 'IsActive' (a nil value)
  1. func - addons/animations/lua/autorun/client/ttttargetclienthit.lua:54
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Alf21** [comment]
addons/weapon-pack2/lua/weapons/weapon_ttt_tigers/shared.lua:202
-> Bloody Knife (I think)

**Comment by dok441** [comment]
Так вы сами это аддон добавляли зараженному как рекомендованный.

**Comment by Alf21** [comment]
It's not linked anymore
