### ISSUE TITLE
2 corpses from the vampire

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#161]
https://www.youtube.com/watch?v=LZBlqyr21Ts
Мы можем увидеть, 2 трупа после смерти vampire, происходит это 50/50.

**Comment by Alf21** [comment]
Thats confusing. Does it happen in a special situation?
Just if he is killed while he is transformed or smth? If not, it seems that this is caused by another addon. But i will give a look as fast as i got some time...
