### ISSUE TITLE
Spartankick fixed bug

### ISSUE THREAD

**Issue by V3kta** [Alf21/TTT2#165]
[[TTT]SpartanKick [FIXED]] lua/weapons/weapon_ttt_spartankick/shared.lua:177: attempt to call method 'GetEyeTrace' (a nil value)
  1. ShootBullets - lua/weapons/weapon_ttt_spartankick/shared.lua:177
   2. unknown - lua/weapons/weapon_ttt_spartankick/shared.lua:141

Got this error while using it.

**Comment by Alf21** [comment]
Thanks, fixed :)
