### ISSUE TITLE
The clairvoyant vdit everything by mistake

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#167]
Произошел баг, человек играя за ясновидящего, стал видеть иконки невиновных над людьми и у кого не было над головой иконки, он был предателем или активом который должен убивать.
https://imgur.com/a/XuWvTQu

**Comment by Alf21** [comment]
Are you using an old version of the Clairvoyant? Normally, since the new update, the clairvoyant should just see roles that are already visible for him.

**Comment by dok441** [comment]
Вроде последняя версия.

**Comment by Alf21** [comment]
I updated it with the last TTT2 update.

**Comment by dok441** [comment]
Последнее обновление "Role HUD Icon for players will just be displayed for team players again" только что поставил. Остальное стояло до этого.
