### ISSUE TITLE
safe log damagelogs off

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#175]
C 8 декабря, логи перестали записываться, видимо вы что-то обновили режиме, что он перестал записывать логи прошлых карт.

**Comment by dok441** [comment]
Ну вы попробуйте, у вас сохраняются логи других карт:?

**Comment by Alf21** [comment]
I never had have logs of any rounds. Maybe something in gmod update broke it...

**Comment by dok441** [comment]
Возможно.
