### ISSUE TITLE
The broken system of delivery of roles.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#178]
Может произойти баг, что дополнительные роли как ясновидящий, выживший не появляются, когда достаточна человек на сервере. А шут после смерти возрождается шутом.

**Comment by Alf21** [comment]
In my latest tests, i didn't noticed any of this issues. Did you have updated the jester and TTT2? Give a look on the new ConVars, especially ttt_min_inno_pct

**Comment by Alf21** [comment]
Set this ConVar to 0 to use the old system (that is in my opinion unbalanced)

**Comment by dok441** [comment]
Я теперь понял, но с шутом проблема есть, но там другой тикет создан.

**Comment by Alf21** [comment]
Okay thanks! Btw. I've found a bug and fixed it. The subroles should get selected properly now.
