### ISSUE TITLE
bug roles

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#179]
Как мы видим, детективов нет вообще, и одни предатели.  
![default](https://user-images.githubusercontent.com/7480655/50056707-df48a600-0181-11e9-846d-eef64dd1b1ee.png)

**Comment by Alf21** [comment]
I tested it with the newest Update (Hotfix#2) and got Hitman / Vampire. Are you sure that you have the newest version? I wrote a comment to inform you about this bugfix. I'm sorry for this issue, but this change was necessary to balance the game

**Comment by dok441** [comment]
Обновление если не ошибаюсь было.
