### ISSUE TITLE
bug weapon

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#180]
![default](https://user-images.githubusercontent.com/7480655/50056716-f38ca300-0181-11e9-9835-9c3a885a2dde.png)
На данном скриншоте, я держу оружие, я выбирал любое и его не было видно, впервые такое вижу, возможно это баг из-за какого-то обновления, но это пока единичный на мне случай.

**Comment by Alf21** [comment]
Hmm keep watching it. Maybe a new bug, but up to now, i never saw anything like that and anything that could cause this..
