### ISSUE TITLE
bugs roles

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#183]
Теперь кроме предателя в ролях "предатель" не выпадает, то есть, хитмана нет, вампира тоже.
Так же не выпадают роли ясновидящий и как в прошлом обращении, выживший.

**Comment by dok441** [comment]
Так же по какой-то причине, у предателя 1 кредит, когда в настройках в !menu стоит 2 кредита при старте.

**Comment by dok441** [comment]
16 человек, шакала и 3 предателя, у предателей, нету роли хитман или же вампир, так же нету выжившего и остальных невинных ролей, кроме детектива.

**Comment by dok441** [comment]
ttt_min_inno_pct 0.4 у меня настроено так.

**Comment by Alf21** [comment]
In my tests, everything works fine. How about the other new sconVars like ttt_max_roles ? And ttt_max_roles_pct?
Did you have the newest version? As i said, there was an hotfix (#2)

**Comment by dok441** [comment]
ttt_max_roles  and ttt_max_roles_pct стандартные настройки. Fix стоит. На счет системы кредитов, понял.

**Comment by dok441** [comment]
Да, опять не полностью видимо обновил. Скоро сделаю перевод на русский, чтоб уже качать нормально обновленную от вас версию =)

**Comment by dok441** [comment]
Все равно система новая пока багует, то есть, есть 3 роли убийцы(2 предателя и маньяк), но нет детектива или же выжившего. Человек на сервере 10.

**Comment by dok441** [comment]
Нет, ясновидящий и выживший не появляются вообще.

**Comment by Alf21** [comment]
Damn, you are right o.O

<img width="637" alt="buggy" src="https://user-images.githubusercontent.com/11843790/50231409-02a46880-03af-11e9-9806-2dd959f41ffe.png">

**Comment by Alf21** [comment]
It's tested with Hotfix#4. This should work. Thanks again!

**Comment by dok441** [comment]
![default](https://user-images.githubusercontent.com/7480655/50235295-5af06000-03d9-11e9-8a26-2f550e61a01d.png)
Как мы видим, детектива нет, а он обязан быть.

**Comment by Alf21** [comment]
Did you tested with Hotfix#4. I runned several tests and everything worked fine now...

**Comment by dok441** [comment]
Только что исправление ваши добавил, перезапустил карту и тут же нету детектива в первом же раунде.

**Comment by Alf21** [comment]
Lol i missed to push the fix xD Sorry, will do it soon, but first of all, i will try to fix the pointshop bug

**Comment by Alf21** [comment]
Should be fixed xD I hadn't got any time to test for now

**Comment by dok441** [comment]
Вроде все нормально.
