### ISSUE TITLE
infected model bug

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#184]
Есть баг, связанный с поинтшопами 1 и 2. Связан он со зараженным, если убьют человека и он станет зараженным и у него будет скин, он не будет зомби, а будет со своим скином, поэтому тут надо я считаю это исправить, чтоб принудительно давался скин зомби.

**Comment by Alf21** [comment]
I understand, but that‘s all in all not a bug of TTT2, but a bug of PS1 and 2

**Comment by dok441** [comment]
Но адаптировать вам необходимо и это возможно. Вы же это понимаете.

**Comment by dok441** [comment]
Вы вроде пытались исправить, но теперь вообще скин не меняется и остается обычная модель из PH

**Comment by Alf21** [comment]
PH ?

**Comment by Alf21** [comment]
I did some changes and tests. Maybe it works, i wasn't able to test it alone. But on local machine, it worked..

**Comment by dok441** [comment]
Все еще не исправлено.

**Comment by Alf21** [comment]
I need more information. The problem is that i can't test it on my own. But I'm able to test it with bots while typing kill and spectating my ragdoll, then respawning. And after respawn, i've my PS model. So why it's still not fixed ? o.O

**Comment by dok441** [comment]
Все просто. Заражает зараженный человек, тот имеет скин, он воскрешается со скином из pointshop 2. Скин даже не пытается изменится.

**Comment by Alf21** [comment]
ah yea... But I don't own PS2 so I can't know how to detect it. And without a detection, I can't do anything :/

**Comment by dok441** [comment]
Эх, а владелец забил на свою работу, ну ладно, будем терпеть =)

**Comment by dok441** [comment]
Вы исправили

**Comment by dok441** [comment]
К сожалению попытка фикса на PH2 не помогло, это чтоб вы просто знали.
