### ISSUE TITLE
Compatibility with Vliss Scoreboard

### ISSUE THREAD

**Issue by BoostedDampi** [Alf21/TTT2#185]
Hi Alf, Is it possible to make the Vliss Scoreboard (https://steamcommunity.com/sharedfiles/filedetails/?id=524266848) compatible with TTT2??

**Comment by dok441** [comment]
Пиши разработчику скрипта, так-как он приватный и не сможет иметь к нему доступ. Пусть разработчик твоего скрипта связывается или сам адаптирует.

**Comment by Alf21** [comment]
As @dok441 said, it‘s not possible.
A) because of the credits (I can‘t release it or resend it. Or more or less can‘t receive it legally from you)
B) it‘s private / have to buy
C) I don‘t own it so I can‘t fix it

**Comment by BoostedDampi** [comment]
Ok, I try to contact the author

**Comment by saibotk** [comment]
The new hud system will be the biggest struggle in making this compatible so im closing the issue

**Comment by TimGoll** [comment]
Additionally we plan on reworking the scoreboard of TTT2. Is there anything you'd like to have added?
