### ISSUE TITLE
hitman no hit

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#186]
https://steamuserimages-a.akamaihd.net/ugc/956351032197826724/46DF9FBAD191088FDF3637D9066EFF5F4694066C/
Как мы можем увидеть, у хитмана почему-то нет цели, случается это редко.

**Comment by Alf21** [comment]
@SchokoShampoo

**Comment by Alf21** [comment]
I pushed an update (fix)

**Comment by dok441** [comment]
Это все еще не исправлено, человек сообщил об этом баге снова.

**Comment by SchokoShampoo** [comment]
Pleasse Test and close
