### ISSUE TITLE
hitman jester hit

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#192]
Был я за Hitman, и моя цель умерла, как вдруг мне дают цель шута, я к сожалению не успел сделать скриншот, как он быстро умер, но факт того, что Hitman выпала цель шут после смерти другой цели, это факт.

**Comment by SchokoShampoo** [comment]
could you check if this is happening again?
If not please close

**Comment by dok441** [comment]
Для начало нужно убийцу исправить, так-как тестировать с шутом, когда у убийцы баги, смысла нет.

**Comment by saibotk** [comment]
@dok441 is this still a thing?

**Comment by dok441** [comment]
У Hitman выпадала цель шут, вот что это =) А дописал я, что нужно исправить баги с Hitman, прежде чем тестировать исправления шута.
