### ISSUE TITLE
Unknown person.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#193]
https://pastebin.com/hf5HTVLj
Можете адаптировать данный скрипт, заключается в том, что вы не знаете игрока ник, если его не видели в лицо, но есть баг, через быстрые команды(Я с кем-то) опознает ник игрока и легко узнать кто он.

**Comment by Alf21** [comment]
hmm yea but as far as i know, that's not a problem related with TTT2 :/ maybe you can ask in the discord whether there is someone that could do so.. Currently i'm very busy.  But maybe I get some time.. Where is this add-on from?

**Comment by Alf21** [comment]
reopen if this is just a thing
