### ISSUE TITLE
Spectator bug

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#196]
![23](https://user-images.githubusercontent.com/7480655/50390858-2f190580-075e-11e9-8d7f-5b68dc4c9660.png)
Текстура при наблюдение есть, из-за чего она, я не знаю, но появилась после последнего обновления.

**Comment by Alf21** [comment]
There is a new Scoreboard TTT2 texture, sure, but nothing else. This can‘t cause this problem AFAIK
