### ISSUE TITLE
The credits for equipment.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#197]
Система установление кредитов за снаряжение более 1, не работает. Я ставил 2 и более, но всегда 1 кредит.

**Comment by Alf21** [comment]
Yea it‘s caused by sql, i did a mistake and already wrote it down in the Workshop. Some Items works, but some are buggy. Currently, just don‘t use this function as far as the indicator for the shop isn‘t finished. Otherwise, this would confuse people too

**Comment by Alf21** [comment]
Sure, I planned to add an indicator with information into the Shop. In the same time, I'm going to switch the current BEM shop with the new BEM Shop by FreshGarry.

**Comment by dok441** [comment]
Я сменил имя предмета, у которого было 2 установлено кредита за него. Но теперь он покупается за 1 кредит, хотя в настройках установлено 2 кредита.

**Comment by Alf21** [comment]
Indicator added.

**Comment by dok441** [comment]
Думаю еще необходимо добавить индикатор со скольких человек можно приобрести экипировку.

**Comment by Alf21** [comment]
The credits indicator is added already. The minPlayers Indicator too. The globalLimited parameter isn‘t implemented yet. But in the next update. This param will restrict access to this equipment if it get bought (just allow 1 amount of this item per round)

**Comment by dok441** [comment]
А где у игрока индикатор со скольких человек предмет можно купить?

**Comment by Alf21** [comment]
There isn‘t any param like this. Do you suggest to change the globalLimited parameter into this suggested one? So that you can decide how often an equipment can be bought?

**Comment by dok441** [comment]
Я сейчас про другое пишу. Я говорю, для игрока пишется, со скольких человек он может купить тот или иной предмет. Вот сколько кредитов он стоит пишет, а со скольких человек нет, было бы хорошо, если бы это тоже писалось.

**Comment by Alf21** [comment]
For this function, use the minPlayers Slider.

**Comment by dok441** [comment]
Я говорю, как клиент, обычный игрок должен знать, когда можно купить это оружие?! У него нет показателя, сколько человек должно, я не про настройку со стороны владельца, а обычного игрока.

**Comment by Alf21** [comment]
You mean there should be a number that shows the minimum amount of needed players for each item in the shop? Currently, if an equipment isn‘t available because of this, there will be a "?" Next to the third icon. Bur yea, I will add an indicator
