### ISSUE TITLE
Breaching Charge Eroor

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#198]
Выдает ошибку оружия при попытке добавить или удалить:
[ERROR] gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:378: bad argument #1 to 'WriteString' (string expected, got nil)
  1. WriteString - [C]:-1
   2. onClick - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:378
    3. OnClick - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:96
     4. unknown - gamemodes/terrortown/gamemode/vgui/simpleclickicon_main.lua:161

[ERROR] gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:387: bad argument #1 to 'WriteString' (string expected, got nil)
  1. WriteString - [C]:-1
   2. onClick - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:387
    3. OnClick - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:96
     4. unknown - gamemodes/terrortown/gamemode/vgui/simpleclickicon_main.lua:161

Addon https://steamcommunity.com/sharedfiles/filedetails/?id=1596554153

**Comment by Alf21** [comment]
That's an issue made by yourself. You need to restart your server after inserting new contents. Items are initialized on the Start. So if you refresh the content and remove the roles and the items on the same way, this wouldn't work. Just restart and everything should work fine...
