### ISSUE TITLE
Error server fakedeath

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#200]
[ERROR] addons/weapon-pack4/lua/weapons/weapon_ttt_fakedeath/hooks.lua:37: attempt to index local 'confirmed' (a boolean value)
  1. fn - addons/weapon-pack4/lua/weapons/weapon_ttt_fakedeath/hooks.lua:37
   2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
    3. IdentifyBody - gamemodes/terrortown/gamemode/corpse_main.lua:56
     4. ShowSearch - gamemodes/terrortown/gamemode/corpse_main.lua:218
      5. unknown - gamemodes/terrortown/gamemode/player_main.lua:461
Использовал я вашу версию под ТТТ2

**Comment by Alf21** [comment]
You should use @lebroomer deathfaker
