### ISSUE TITLE
error client

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#201]
[ERROR] addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:37: attempt to call method 'GetSubRole' (a nil value)
  1. func - addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:37
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Alf21** [comment]
That‘s not an Add-On of TTT2. You should contact Tobse (Co-Creator of TTT Totem).
