### ISSUE TITLE
ERROR server important

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#205]
[ERROR] gamemodes/terrortown/gamemode/vgui/sb_row_main.lua:279: attempt to index global 'sboard_panel' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/vgui/sb_row_main.lua:279

**Comment by Alf21** [comment]
What was the reason of this error?

**Comment by dok441** [comment]
Думаю это моя ошибка.

**Comment by Alf21** [comment]
Yea i think the same :D
