### ISSUE TITLE
Non-working invisibility

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#206]
Заметил, что люди начали сообщать, что все вещи у которых есть невидимость, начали не работать, то есть, в невидимость ты больше не входишь, это после вашего последнего обновления.

**Comment by Alf21** [comment]
Hmm.. I didn't changed anything related to this. Just the Shop, the ShopEditor and Russian translation.

**Comment by dok441** [comment]
Я сам был удивлен.

**Comment by Alf21** [comment]
Do you have an example or an image of that? SO that i can try to reproduce

**Comment by dok441** [comment]
https://youtu.be/LeKFwcB4j-o?t=30
