### ISSUE TITLE
The eternal round is also not present to it the end

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#208]
https://www.youtube.com/watch?time_continue=56&v=GKENhjDgi94
Был обычный раунд и карта сломалась, просто ничего не происходило после окончание, на видео это прекрасно видно.

**Comment by Alf21** [comment]
I never experienced any error like this in the newest versions. Maybe some errors somewhere?

**Comment by dok441** [comment]
[ERROR] gamemodes/base/entities/weapons/weapon_base/shared.lua:244: attempt to call method 'GetAmmoCount' (a nil value)
  1. Ammo1 - gamemodes/base/entities/weapons/weapon_base/shared.lua:244
   2. DrawWeapon - gamemodes/terrortown/gamemode/cl_wepswitch_main.lua:98
    3. Draw - gamemodes/terrortown/gamemode/cl_wepswitch_main.lua:160
     4. unknown - gamemodes/terrortown/gamemode/cl_hud_main.lua:378

[ERROR] gamemodes/terrortown/gamemode/cl_equip_main.lua:43: table index is nil
  1. GetEquipmentForRole - gamemodes/terrortown/gamemode/cl_equip_main.lua:43
   2. func - addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:37
    3. unknown - lua/includes/extensions/net.lua:32

Клиентские ошибки, серверные потом гляну.

**Comment by Alf21** [comment]
This error is caused by a buggy Item / Weapon. That doesn't belong to TTT2. 😕
