### ISSUE TITLE
Bug with purchase of weapon as armor, the radar.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#210]
Не работает покупка брони, радара. Нажимаю купить и ничего не происходит.

**Comment by dok441** [comment]
Странно, посмотрю что у меня.

**Comment by Alf21** [comment]
Maybe you use the RandomShop option without a compatible Shop Add-On. Currently, just the normal TTT2 shop supports it.

**Comment by dok441** [comment]
Я установил non-random, но оружие все равно не покупается.

**Comment by Alf21** [comment]
Do you use custom shops?

**Comment by dok441** [comment]
Ваш магазин, оружие самое главное не покупается только то, которое пассивное, как радар, броня, маска.

**Comment by dok441** [comment]
Всё, вы починили.
