### ISSUE TITLE
Error shopeditor

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#213]
[ERROR] gamemodes/terrortown/gamemode/shared_main.lua:549: attempt to compare nil with string
  1. unknown - gamemodes/terrortown/gamemode/shared_main.lua:549
   2. sort - [C]:-1
    3. SortEquipmentTable - gamemodes/terrortown/gamemode/shared_main.lua:553
     4. CreateItemEditor - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:277
      5. DoClick - gamemodes/terrortown/gamemode/cl_shopeditor_main.lua:902
       6. unknown - lua/vgui/dlabel.lua:232
При попытке открыть меню shopeditor

**Comment by dok441** [comment]
[ERROR] gamemodes/terrortown/gamemode/equip_items_shd_main.lua:529: bad argument #1 to 'lower' (string expected, got nil)
  1. lower - [C]:-1
   2. GetEquipmentFileName - gamemodes/terrortown/gamemode/equip_items_shd_main.lua:529
    3. GetEquipmentItemByName - gamemodes/terrortown/gamemode/equip_items_shd_main.lua:536
     4. GetEquipmentByName - gamemodes/terrortown/gamemode/equip_items_shd_main.lua:545
      5. ReadItemData - gamemodes/terrortown/gamemode/sh_shopeditor_main.lua:74
       6. func - gamemodes/terrortown/gamemode/cl_init_main.lua:365
        7. unknown - lua/includes/extensions/net.lua:32

**Comment by Alf21** [comment]
That's an error caused by any other addon

**Comment by Alf21** [comment]
This happens, if there is a buggy Item (passive item) without a valid id

**Comment by dok441** [comment]
Да, есть пассивный предмет, но раньше этого не было, может это исправить?

**Comment by Alf21** [comment]
I can't fix this because it's not caused by TTT2. I could implement a check, but I don't wanna support buggy add-ons to be on this world

**Comment by dok441** [comment]
Okey
