### ISSUE TITLE
Open item purchase menu dead

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#214]
По какой-то причине, я могу открывать находясь за мертвого предателя меню покупки предметов.
![default](https://user-images.githubusercontent.com/7480655/50849822-2a249a80-1389-11e9-9d5e-fb2dc709817a.png)

**Comment by Alf21** [comment]
Yea, since the new update, you are able to update your own shop at this time. Just select the role and set your favorites / give a look on some new equipment.

**Comment by dok441** [comment]
Okey
