### ISSUE TITLE
bug shopeditor saved settings

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#215]
Я заметил баг, а именно с сохранением настроек вещей, у меня постоянно отбрасывает радар к настройкам, что он ограничен на 1 человека, я его постоянно сбрасываю, а он очень часто сбрасывается то на следующей карте или после рестарта и это очень раздражает.

**Comment by Alf21** [comment]
Does this happen with every item or just with the radar, armor, disguiser and c4?

**Comment by dok441** [comment]
У меня происходит только с радаром.

**Comment by Alf21** [comment]
Hmm.. that doesn't make any sense. Did you use a modified radar?

**Comment by dok441** [comment]
Нет, обычный радар.

**Comment by dok441** [comment]
Я удалил базу данных, сейчас вроде нормально работает, видимо надо было это сделать, пока не замечал каких-то проблем, время покажет.
