### ISSUE TITLE
A small miscalculation with the purchase menu opening from the dead

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#216]
Есть один недочет с тем, что когда ты мертв, ты нажимаешь на С и это меню покупки предметов, но на эту же букву на С, назначена победительное меню и ты в итоге нажимаешь на С в конце раунда, а открывается меню покупки предметов, вместо того, чтоб открылось меню раунда, кто победил и тд.

**Comment by saibotk** [comment]
This is working as it should, this was implemented with the new shop update, you can disable this, in the F1 Settings under "BEM" -> General 
There is a checkbox to change this behaviour.

**Comment by dok441** [comment]
Не подскажите, где отключить для всех по умолчанию, чтоб она была выключена изначально у всех.

**Comment by dok441** [comment]
Нашел.

**Comment by dok441** [comment]
Параметр не работает, я выключил, но окно все равно появляется.
