### ISSUE TITLE
Bug with connecting a new player and eternal round.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#219]
Ничего не предвещало беды, обычная смена карты и тут хоп. Один человек как видно на картинке, просто находится в наблюдателях.
![default](https://user-images.githubusercontent.com/7480655/50925103-62e47280-1462-11e9-90f4-448b10c3171b.png)
После его убийства, раунд не заканчивался, а просто ушел в 0 и длился бы вечно.
![default](https://user-images.githubusercontent.com/7480655/50924986-1ac55000-1462-11e9-8882-3479982f8034.png)
После рестарта раунда, это не помогло и после подготовки, началась новая на 4 минуты и помогла только смена карты.
![22](https://user-images.githubusercontent.com/7480655/50925240-ca022700-1462-11e9-9986-c940d8812025.png)

**Comment by dok441** [comment]
[ERROR] gamemodes/terrortown/gamemode/traitor_state_main.lua:205: bad argument #1 to 'WriteUInt' (number expected, got nil)
  1. WriteUInt - [C]:-1
   2. unknown - gamemodes/terrortown/gamemode/traitor_state_main.lua:205
Похоже эта ошибка это вызвало. 
Так же на следующей карте это произошло, через 1 раунд.

**Comment by Alf21** [comment]
ok ty, should be fixed. Idk why this happen. But it seems to be a buggy delayed gmod init.

**Comment by Alf21** [comment]
Hmm these links are invalid....

**Comment by dok441** [comment]
Там скин из hl2 и человек может слышать живого. А так же баг с раундом. Так же замечу это в новых версиях, в стабильной не замечал такого. Скриншоты к сожалению копию не делал, человек удалил -(

**Comment by Alf21** [comment]
hmm then we need to wait for the new error :/
