### ISSUE TITLE
Error client

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#222]
[ERROR] gamemodes/terrortown/gamemode/cl_equip_main.lua:245: attempt to call method 'IsEquipment' (a nil value)
  1. CreateEquipmentList - gamemodes/terrortown/gamemode/cl_equip_main.lua:245
   2. OnSelect - gamemodes/terrortown/gamemode/cl_equip_main.lua:592
    3. ChooseOption - lua/vgui/dcombobox.lua:94
     4. DoClick - lua/vgui/dcombobox.lua:175
      5. OnMouseReleased - lua/vgui/dlabel.lua:232
       6. unknown - lua/vgui/dmenuoption.lua:77
Выдало ошибку, когда хотел посмотреть детектива, 2 раз нормально открыло. Это было во время конца раунда.

**Comment by saibotk** [comment]
same as #256
