### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#224]
[ERROR] addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:37: attempt to call method 'GetSubRole' (a nil value)
  1. func - addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:37
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Alf21** [comment]
wrong add-on, but @saibotk is the creator.

**Comment by saibotk** [comment]
The addon was updated and this might not occur anymore, if so please reopen this issue
