### ISSUE TITLE
Passive Effect Items in ShopEditor

### ISSUE THREAD

**Issue by FreshGarry** [Alf21/TTT2#229]
**Describe the bug**
I have configured some Passive Effect Items (Bodyarmor, Radar, BlueBull) just for test reasons as .NoRandom, .notBuyable and teamLimited. Now i dont want that settings to be like that so i tried to change them but after a game restart they are set back to the old ones. Unluckily i am not 100% sure that my game did not crash since I had that configuration.

**To Reproduce**
Steps to reproduce the behaviour:
I have checked the boxes some days ago in the different items and saved it.
Now I have unchecked the Boxes, saved again and restarted the game.
After that they are checked again.

**Expected behaviour**
Just saving the new settings :)

**Desktop (please complete the following information):**
- no errors
- happens with only TTT2, ULX, ULIB, ULX for TTT2 and TTT2 Animations activated

**Additional context**
I am running a local (from Gmod on win10) hosted server.

**Comment by dok441** [comment]
Тоже была такая проблема, единственное решение на данный момент, удали из базы данных настройки оружия и сделай заново и у тебя будет все нормально.

**Comment by TheNickSkater** [comment]
Also had the same issue with some items. Not sure if it were only passive items but yeah.
