### ISSUE TITLE
Saving of shop item costs not working

### ISSUE THREAD

**Issue by V3kta** [Alf21/TTT2#236]
Everytime the map changes or the server restarts, costs for Items I changed reset. I have set the cost for Radars to 2 (a while ago), which saved, but now I can't change it back to 1, it only works for the map currently played. Got the tip to change the cost and then use the exit command to close the server, which didn't work either.

**Comment by dok441** [comment]
Delete the database on items and it will be fine.

**Comment by Tobiti** [comment]
Where is the location of the database file?

**Comment by dok441** [comment]
sv.db

**Comment by V3kta** [comment]
Yea, where is it located? And then all my changes are reverted back, and if I can't save afterwards?

**Comment by dok441** [comment]
After removing everything will work fine

**Comment by V3kta** [comment]
Okay thx

**Comment by Alf21** [comment]
Does it work now? I've found a bug in the saving system...

**Comment by V3kta** [comment]
Not sure, couldn't try and I didn't delete the db, I edited it. But I will delete it and tell you.

**Comment by Alf21** [comment]
Any feedback?

**Comment by V3kta** [comment]
Well it saves now. No more problems with that.
