### ISSUE TITLE
Small window describe weapons

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#237]
Возможно ли сделать, чтоб в окошке можно было листать вниз, чтоб текст влазить, так-как сейчас оно очень маленькое, на картинке видно, как текст обрывается.
![default](https://user-images.githubusercontent.com/7480655/51787374-d2f93500-2192-11e9-921c-2143df16c125.png)
Я думаю необходимо сделать ползунок, чтоб люди могли прокрутить и дочитать.

**Comment by saibotk** [comment]
I'll put that on my todo list, and do it as soon as i can find some sparetime
