### ISSUE TITLE
no working ttt weapon

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#250]
I also note that objects are not displayed as mines, which should be visible through the walls.
So the same gun, Newton not pushing people.

**Comment by dok441** [comment]
It still doesn't work and it's important, because it's not the only weapon that isn't highlighted to all the traitors and they die.

**Comment by Alf21** [comment]
I don't know what you mean. I never experienced any bug like this. Keep sure that it's not caused by any other add-on. This bug wasn't reported by other users so I think it's not caused by TTT2

**Comment by dok441** [comment]
Только вот на стабильной версии ттт2, все работает хорошо. А на последней версии их не видно.
