### ISSUE TITLE
What's it?! Bug or feature?

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#258]
Словил я веселье от происходящего, но в один прекрасный момент, на пару раундов у людей начались проблемы с головами, это конечно забавно, но встречал я такое только в ТТТ =)
![default](https://user-images.githubusercontent.com/7480655/52917144-bbcce380-3309-11e9-8469-40bfde38708d.png)

**Comment by Alf21** [comment]
THats a common bug in gmod. Not specially in TTT or TTT2. But it often happens there because there a buggy add-ons causing it. E.g. the harpoon. It's reasoned in bone manipulating. Check Bone Fix or Harpoon Fix addons
