### ISSUE TITLE
Error weapon update

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#260]
[ERROR] gamemodes/terrortown/gamemode/client/cl_wepswitch.lua:101: attempt to call global 'MakeKindValid' (a nil value)
  1. DrawWeapon - gamemodes/terrortown/gamemode/client/cl_wepswitch.lua:101
   2. Draw - gamemodes/terrortown/gamemode/client/cl_wepswitch.lua:151
    3. unknown - gamemodes/terrortown/gamemode/client/cl_hud.lua:414

In the new update gives an error in the selection of weapons.

**Comment by lebroomer** [comment]
Thank you. Seems like I forgot to commit a important change.

**Comment by dok441** [comment]
Your correction has fixed everything, thank you.
