### ISSUE TITLE
error weapon update

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#262]
[ERROR] gamemodes/terrortown/gamemode/shared/sh_inventory.lua:22: attempt to compare number with nil
  1. MakeKindValid - gamemodes/terrortown/gamemode/shared/sh_inventory.lua:22
   2. AddWeaponToInventory - gamemodes/terrortown/gamemode/shared/sh_inventory.lua:69
    3. CleanupInventory - gamemodes/terrortown/gamemode/shared/sh_inventory.lua:48
     4. func - gamemodes/terrortown/gamemode/client/cl_inventory.lua:2
      5. unknown - lua/includes/extensions/net.lua:32

It happened at the start of the round.

**Comment by lebroomer** [comment]
Mmh thats pretty weird. It would mean that a weapon in your inventory is not compatible with TTT and that shouldn't happen. I haven't received this error at all. On which map and with which collection did you get that error?

**Comment by dok441** [comment]
Weapons standard, it happened at the beginning of the round when people have uploaded to the server and started to prepare.
