### ISSUE TITLE
Error displaying active role

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#263]
Как мы можем увидеть, я показываюсь в таблице зеленым, хотя роль моя невиновным. Если мы откроем логи, то там так же считает система, что я активная роль, но роль моя невиновный, почему это произошло, я не знаю.
![default](https://user-images.githubusercontent.com/7480655/52919000-5c79ce00-331f-11e9-8e4d-803a480c7e1c.png)

**Comment by dok441** [comment]
I believe it has to do with the survivor.

**Comment by Alf21** [comment]
I didn't updated TTT2 main branche or networking a long time....

**Comment by Alf21** [comment]
So on, it's duplicated: #239
