### ISSUE TITLE
A round that didn't end...

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#285]
В последней версии есть проблема, когда раунд закончился, была победа зараженных, новый раунд не начинался, решение рестарт раунда или смена карты. По какой причине или какая связь, я еще не определил.

**Comment by Alf21** [comment]
Maybe a bug with SetSubRoleModel? Should be fixed in the newest version AFAIK

**Comment by dok441** [comment]
Проблема все еще есть.

**Comment by Alf21** [comment]
Any error? The need to be one..

**Comment by dok441** [comment]
Ошибок нету, просто раунд закончился и новый не начинался, в тот раз ошибок тоже не было.

**Comment by Alf21** [comment]
Hmm without any error, I can't do anything.

**Comment by dok441** [comment]
Понимаю.

**Comment by dok441** [comment]
Вот пару минут назад этот же баг произошел и подозреваю я связан он с шутом. Раунд закончился, но оставался шут(он стал невиновным) и предатель.  Победа была предателей. В итоге они просто бегали, раунд новый не начинался.
