### ISSUE TITLE
Logs 63 damage, in fact much less miracle?

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#286]
Я заметил, что из-за спринта урон стал гораздо меньше проходить по людям, ты стреляешь в голову в упор, а он может не умереть, это не всегда, но зачастую. Возможно я могу ошибаться и это не связано с ускорением, но ничего особого не менялось, единственное это ускорение. Я отключу и проверю лично, если это так, то напишу.

**Comment by dok441** [comment]
Я проверил и нет, спринт не влияет на это. Я стреляю в человека с дробовика, логи пишут 63 урона, а у него осталось 64 hp, урон то есть по факту гораздо меньше, я не знаю что вы сделали, но что-то не так. Это не всегда, но часто, тикрейт сервера 60, не должно никаких особых проблем быть.

**Comment by Alf21** [comment]
I've heard from this bug in another community. Idk what the reason is, but AFAIK we don't modify the damage. Maybe another buggy add-on?
