### ISSUE TITLE
karma set role failed save

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#289]
При попытке сохранить в настройках через ulx, минимальное значение кармы для определения роли, при смене карты сбрасывается.

**Comment by saibotk** [comment]
Ok i tried setting the percentage for a role via ULX and it worked for me after a map change.
So can you give me some more information about this, like which role in particular you were trying to adjust and the version of TTT2 you used?

**Comment by dok441** [comment]
Recent version. I must clarify that this is an attempt to change the ulx in the Department of TTT, when you change the value of cvar is not even written in the chat, if you change for example the detective at once reported the change, and with the other roles there was no response.
(Original Последнюю версию. Я уточняю, это попытка изменять в ulx в отделе ТТТ, когда ты меняешь значение, даже cvar не пишутся в чат, если ты меняешь  к примеру детектива, то сразу сообщает изменения, а с другими ролями никакой реакции.)

**Comment by saibotk** [comment]
I still cannot reproduce the issue, do you mean the "ttt_ROLENAME_pct" convar?

**Comment by dok441** [comment]
ttt_detective_karma_min как пример.

**Comment by saibotk** [comment]
i see, and this is not working on other roles right? 
I have also noticed this bug and already put it on our Todo list :+1:

**Comment by dok441** [comment]
Что-то фикс просто убрал теперь в ulx эту функцию.

**Comment by dok441** [comment]
С последнем патчем функция была добавлена, но она опять не сохраняет настройки.
