### ISSUE TITLE
Disable run on shift

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#290]
Так-как тут система спринта уже установлена, то предлагаю отключить стандартный бег на shift, во 1 он не актуален, во 2 говорить с командой на shift. Он установлен в ТТТ по стандарту, он не дает сильную скорость, но вы можете услышать разницу бега по звуку ходьбы.

**Comment by saibotk** [comment]
There is no default sprint as far as i know, the +sprint bind is just used by TTT to speak to your team if your team has its own voice chat, which is currently under development to make this button dynamic / changeable in the new Bindings category of the F1 menu.

**Comment by dok441** [comment]
Он есть, протестируйте сами, нажмите шифт и побегайте, вы даже услышите как ваши шаги будут сильнее и чутка совсем быстрее.

**Comment by TimGoll** [comment]
Yes, there is a sprint system included in TTT2, but it isn't bound to any key per default.

**Comment by dok441** [comment]
Нет, понимаете она есть даже в обычным ТТТ, она никак не показывается, нету индикатора или чего-то. Вам достаточна протестировать это, а взять пробежать без SHIFT и потом зажать SHIFT и вы увидите, что вы пробежали быстрее, а так же ваши шаги будут громче, я сам вспомнил не так давно, об этом многие не знают, так-как на SHIFT люди привыкли говорить с предателями.

**Comment by saibotk** [comment]
OK i just tried what you were talking about, but i really cannot see any difference and there is at least in my local test environment no difference in sound or speed.

**Comment by TimGoll** [comment]
I can confirm @saibotk s statement. I've tried it just now and there is no sprint in TTT. Maybe you've installed an addon?

**Comment by dok441** [comment]
Я конечно еще раз протестирую без всех аддонов, но вроде как это давно уже есть.

**Comment by TimGoll** [comment]
Please reopen if this problem still exists
