### ISSUE TITLE
The problem of determining the steamid

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#295]
[ERROR] addons/mapvote/lua/mapvote/cl_mapvote.lua:58: attempt to call method 'SteamID' (a nil value)
  1. func - addons/mapvote/lua/mapvote/cl_mapvote.lua:58
   2. unknown - lua/includes/extensions/net.lua:32

Я видел, что вы пытались решить данную проблему, но как видно по результату, бывают все еще ошибки, связанные с определением steamid.
Такое в первый раз, означает проблемы именно в самом режиме.

**Comment by Alf21** [comment]
That doesn‘t have anything to do with this addon :/

**Comment by dok441** [comment]
This has never happened, it's certainly not critical, okay.

**Comment by Alf21** [comment]
In combination with another mapvote issue I‘m going to review it tomorrow

**Comment by Alf21** [comment]
Since which update this happened? (pls name it exactly if you can)

**Comment by dok441** [comment]
Точно когда выкатили большую обнову.  А если быть точнее Commits on Mar 5, 2019 после этих изменений точно была уже ошибка.

**Comment by TimGoll** [comment]
It might have something to do with my Steam ID 64 changes? But I couldn't imagine how that changed anything

**Comment by Alf21** [comment]
There have been hundreds of updates in this single update. This doesn't help :/

**Comment by dok441** [comment]
I unfortunately can not say 100%, this error occurred 2-3 times when the card was changed, so I said, not critical.

**Comment by Alf21** [comment]
But it's critical because this error theoretically can't occur.

**Comment by dok441** [comment]
Я к сожалению не могу помочь в этом вопросе, сейчас я не замечал данной ошибки.

**Comment by Alf21** [comment]
Reopen if it appears again :)
