### ISSUE TITLE
error client

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#296]
[ERROR] gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua:472: attempt to index global 'sboard_panel' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua:472

[ERROR] gamemodes/terrortown/gamemode/shared/sh_init.lua:439: attempt to index a nil value
  1. EquipmentIsBuyable - gamemodes/terrortown/gamemode/shared/sh_init.lua:439
   2. CreateEquipmentList - gamemodes/terrortown/gamemode/client/cl_equip.lua:366
    3. unknown - gamemodes/terrortown/gamemode/client/cl_equip.lua:515
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by Alf21** [comment]
fixed or some debugs now?
