### ISSUE TITLE
Unknown and double rebirth

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#299]
Неизвестный возродился 2 раза. 1 раз когда его убили, 2 раз по какой-то не известной мне причине, из-за чего сказать сложно.
Ситуация такая, его убивает невиновный, он возрождается. Убивает шпиона, перестреливается с предателем и падает. Потом внезапно он возрождается на краю и его что-то толкает и он падает, то есть он возродился еще раз после 2 смерти... Логи к сожалению этого не показывают, но человек не врёт.

**Comment by Alf21** [comment]
I'm sorry but it's not possible to translate this text :/

**Comment by dok441** [comment]
В кратце, неизвестный возродился 2 раза, хотя должен 1 раз. По какой причине, я не знаю.

**Comment by Alf21** [comment]
Ty Dok!
