### ISSUE TITLE
External HUD Addon Support

### ISSUE THREAD

**Issue by BoostedDampi** [Alf21/TTT2#30]
Is it possible to make a HUD addon work with TTT2?? 
ES. (https://steamcommunity.com/sharedfiles/filedetails/?id=325000783)
I don´t like the normal TTT HUD and I love this HUD, but I can´t use it because it is not compatible with TTT2.

**Comment by Alf21** [comment]
Sure, I like this addon too. But I'm just able to make it compatible if the author of this addon accept that I reupload this addon. I don't think so. As a result, a) the author needs to make it on his own or b) he needs to communicate with me.

**Comment by Alf21** [comment]
yea I'm sorry, but that's the only way we can do so :( I already send him a friendship request to open communication...

**Comment by BoostedDampi** [comment]
Good, I can try to ask him in the comments under his Addon

**Comment by Alf21** [comment]
Alright. For now, this should work: https://github.com/Alf21/TTT_Octagonal_HUD
Please give me an example where to place the team icon :)

**Comment by BoostedDampi** [comment]
With Team Icon do you mean the icons over the heads of teammates??

**Comment by Alf21** [comment]
No this team icon in the HUD: https://steamuserimages-a.akamaihd.net/ugc/938331559626522870/6CAE8ED3A454E27D879F34D8F503D7077D1D43DD/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black

**Comment by BoostedDampi** [comment]
I have sincerely never seen an icon like this…  but I think you can put it here https://www.dropbox.com/s/8l5ynyzjwuxso33/20181028142615_1.jpg?dl=0

**Comment by BoostedDampi** [comment]
ok! Thanks

**Comment by Alf21** [comment]
![20181104144842_1](https://user-images.githubusercontent.com/11843790/47965076-83e3ae00-e042-11e8-80fb-27da58e05d4b.jpg)

**Comment by BoostedDampi** [comment]
That’s Cool, I don´t now if this is the right place to ask, but is there a date when the new TTT2 is released??

**Comment by Alf21** [comment]
Currently, the newest version is available in the workshop with every ttt2 add-on included called TTT2 Beta.
The main TTT2 workshop add-on will be updated as far as all tests got finished. There shouldn't be any bugs ^^

**Comment by BoostedDampi** [comment]
Because for now in the description is written that the addon is not compatible with RDM-manager, so we can´t use it for now?

**Comment by Alf21** [comment]
hum... On my server, it is compatible with the RDM Manager. And as far as I know, with the SpecDM too. But it doesn't override the SpecDM HUD.

**Comment by BoostedDampi** [comment]
Hello Alf, is the Octagonal Hud Fixed version working with the last version of TTT2 (0.3.7.3b)??

**Comment by Alf21** [comment]
Oups, i need to fix the icons, soon (in 2 hours i think)

**Comment by H3xxdump** [comment]
Hey, the Jackal is not working for us (@BoostedDampi and me). Everytime you get Jackal the Hud gets bugged. Furthermore you get an Script Error.

**Comment by Alf21** [comment]
> 
> 
> Oups, i need to fix the icons, soon (in 2 hours i think)



> 
> 
> Hey, the Jackal is not working for us (@BoostedDampi and me). Everytime you get Jackal the Hud gets bugged. Furthermore you get an Script Error.

as i said ^^

**Comment by Alf21** [comment]
Okay should be fixed. Use the newest TTT2 version and newest Octagonal Hud version :)

**Comment by BoostedDampi** [comment]
Ok Thanks
