### ISSUE TITLE
Confirmation of death hundreds of times

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#301]
Баг заключается в том, что смерть можно подтверждается сотни раз, из-за чего это происходит я не знаю, но оповещение все идет и идет. Вот не давно была ошибка с шутом, его убили, он стал сообщником шакала, он умер его смерть начал подтверждать человек и это оповещение всплывало очень долго, около 30 раз, пока он не прекратил.

**Comment by Alf21** [comment]
#280 doublicated
