### ISSUE TITLE
Break PH2 it big update TTT2

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#303]
Error https://pastebin.com/vKgzurxd
Файлы связанные с ошибкой:
cl_dpointshopmanagementtab_settings https://pastebin.com/71sxdYgk
Проблема с PH2, когда вы выкатили обновление с новым HUD и так далее, вы что-то изменили, что полностью сломало его работу, я хотел бы выяснить, что вы сделали, что повлекло к такому, данная ошибка конечно связанна только при открытии администратором меню, если игрок открывает, у него все работает.

**Comment by Alf21** [comment]
Did you uploaded the wrong file? I couldn‘t find any line associated with the error...

**Comment by dok441** [comment]
Fixed file

**Comment by Alf21** [comment]
Random duplicated names ^^
