### ISSUE TITLE
New Role: Pirate

### ISSUE THREAD

**Issue by Skatcat** [Alf21/TTT2#306]
(I wanted to call this role 'Mercenary', but I think 'Pirate' just sounds more unique and fun. And it's still fitting.)

EDIT: Removed the Pirate being evil without a contractor and being announced.

### **Pirate**

**Basic description**

The Pirate starts off as a neutral role. He doesn’t really care about what’s good and what’s evil… all that matters is, that there’s money involved. 

As long as another person owns the Pirate’s contract, he’s on the same team as them.

**Role abilities and Gameplay**

The Pirate spawns with an item called the ‘Contract’.

The Contract doesn’t have any direct abilities. It is, however, what binds the Pirate to another player: If the Pirate throws the Contract and it gets picked up by someone, he’s automatically on the same team as this person, his ‘contractor’.

The Pirate doesn’t gain his teammate's abilities, but he can follow his orders and basically becomes somewhat of a sidekick. Additionally, the Pirate doesn’t know his contractor’s role. But honestly: Pirates don’t care who it is, as long as they get paid.

However, since the Contract is what binds the Pirate to his team: When his contractor dies, the Contract is dropped. Whoever picks it up will be the Pirate’s new boss.

The Contract cannot be dropped manually by a contractor. Once he’s picked it up, only death can remove it from his inventory!

The Pirate can’t deal damage to his own contractor.

Under contract, the Pirate loses Karma and Points like his contractor would. (For example: A Pirate under an Innocent’s contract will lose Karma for killing an innocent.) The same applies the other way around. Don’t blindly kill a Pirate under contract. He might be on your side for now!

If the Contract isn’t picked up by anyone after a certain amount of time, it automatically goes back to the Pirate’s inventory. This is to prevent losing the Contract somewhere.

In a game with multiple Pirates, only one of the Pirates spawns with the Contract. The contractor will rule every single Pirate in the game. Have fun with your army of mercenaries!

**Win conditions**

The Pirate wins with his contractor’s team.

**Why it might be interesting**

This is just a fun role for open alliance building but the Contract also allows for some really janky combinations, like teaming with a Jester etc.

**Interactions with other roles**

Giving the Contract to Innos, Traitors, SK, Jack etc. is the most basic kind of contract. They'll have +1 teammate and also they'll value their life more for a while. After all, who knows, if they die, you might turn against their team...

Giving the Contract to the Detective is probably the safest way of joining the good side for the Pirate.

Giving the Contract to the Jester is a huge gamble. Once the Jester has it, there’s no way the Pirate can change teams since only the Jester’s death can drop the Contract. However, the Pirate, unlike the Jester, will be able to deal damage. This means the Jester can make him run amok to get them both killed eventually.

Giving the Contract to the Unknown will do nothing since the Unknown can’t win without being killed and assimilating another role.

**Comment by Alf21** [comment]
TTT-2/ttt2-role_pir

**Comment by lebroomer** [comment]
It's realeased: https://steamcommunity.com/sharedfiles/filedetails/?id=1737101500
