### ISSUE TITLE
Removing 90% propkill.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#309]
У меня есть хорошая идея, чтоб убрать 90% PropKill. Для этого стоит сделать, если ты берешь магнитной палкой предмет, то выключается столкновение с этим предметом у людей, а так же если он отпускает предмет, то еще в течении 15 секунд эффект действует, это полностью уберет толкание людей предметами а так же в 90% уберет propKIll, единственное что останется, это если в предмет стреляешь, он летит и убивает человека.

**Comment by Alf21** [comment]
Why should we remove Propkills?

**Comment by dok441** [comment]
Как понять почему? Это бывает сложно отслеживать, если человек умеет использовать эту лазейку, он может убивать людей, это потом в логах не доказать. Карма за это не снижается, поэтому это можно сказать лазейка, как и геморой для администрации.

**Comment by Alf21** [comment]
Yea but that's no reason to remove propkills for everyone. Props are usable and made to use them for killing.

**Comment by dok441** [comment]
Я же не говорю про взрывчатые бочки, я говорю про обычные бочки, которыми кидают и люди умирают, это всех раздражает и мешает администрации точн установить, если карта сменилась, убивал ли он его, вы понимаете, что это открывает лазейку и дополнительный геморой в сам режим? Единственные кто может по задумке убивать пропами это спектаторы, но они итак смогут их убивать, тяжелые пропы не взять магнитной палкой =) А предали не должны убивать пропами, это бред.

**Comment by Alf21** [comment]
I'm talking as well about normal props and normal barrels. I never pronounced the word "explosive". IMO removing prop kills will remove a fun factor and a feature of TTT. If you want, you can create a ConVar and make a pull request as well.

**Comment by dok441** [comment]
Вот забавно ходить убивать бочкой, ему карму не снимает, а потом люди в отместку убивают его и теряют карму, очень весело людям. Видимо понимания режима у нас разные.
