### ISSUE TITLE
The spy - traitor-karma

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#312]
Может произойти баг, если предатель убивает шпиона, тебе засчитают как за убийство твоего товарища по команде и в итоге ты теряешь карму.

**Comment by Alf21** [comment]
You will never lose karma for killing a spy. Since the spy is an inno and the calculations are handled by the server

**Comment by dok441** [comment]
При мне человек убил шпиона, он был предателем, он потерял карму. Логи врать не могут и он сам =)

**Comment by Alf21** [comment]
Then you need to show me the protocol. :)
