### ISSUE TITLE
No Hud

### ISSUE THREAD

**Issue by WorldEdit29** [Alf21/TTT2#313]
Hello Alf21,

Im playing on a local server with my friends and im hosting it.
yesterday we played ttt and everythings works fine. but today
as we start we dont have a hod and cant pick up Weappons, but the shot for T works.

On the top left comes a message:

,,TTT2 is Creating Errors, check console for more details"

and the console spam this message:

[[TTT2] Classes for Trouble in Terrorist Town] lua/classes/client/cl_hud.lua:106: attempt to index local 'hud' (a nil value)
  1. ClassesInfo - lua/classes/client/cl_hud.lua:106
   2. v - lua/classes/client/cl_hud.lua:414
    3. unknown - lua/includes/modules/hook.lua:84

I hope you can help us :)

My Steam Profile:
https://steamcommunity.com/profiles/76561198149233535/

My Collection:
https://steamcommunity.com/sharedfiles/filedetails/?id=1686176870

![20190317212101_1](https://user-images.githubusercontent.com/48657791/54497441-ec993c00-48fa-11e9-8a58-444e6e5b4dff.jpg)

![20190317212129_1](https://user-images.githubusercontent.com/48657791/54497443-ec993c00-48fa-11e9-875f-86cbb1bd0ab9.jpg)

**Comment by Lxk3y** [comment]
This issue has been fixed. Try restarting your server or reinstalling TTT2.

**Comment by SLoW432** [comment]
i still have the same issue even after reinstalling

**Comment by TimGoll** [comment]
fixed in last release, please redownload from the workshop
