### ISSUE TITLE
error client target

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#316]
[ERROR] gamemodes/terrortown/gamemode/client/cl_targetid.lua:327: 'TargetIDSmall' isn't a valid font

  1. SetFont - [C]:-1
   2. Call - gamemodes/terrortown/gamemode/client/cl_targetid.lua:327
    3. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:97

**Comment by Alf21** [comment]
Never had this issue. When will this appear?

**Comment by dok441** [comment]
In the latest updates

**Comment by TimGoll** [comment]
Sure. But when does it happen. We can only fix it if we're able to reproduce it.

**Comment by Alf21** [comment]
Open if you can explain this issue in detail. Because it doesn‘t appear normally and does not reduces the functionality, this seems to be caused by an external add-on.
