### ISSUE TITLE
[TTT2][ERROR]Incompatible Add-On

### ISSUE THREAD

**Issue by xopez** [Alf21/TTT2#318]
Hello,
Just wanted to leave you an incompatible addon. Since I am new to your collection i don't know if it works or not.
Thats all

**Comment by saibotk** [comment]
What are you trying to tell us?

**Comment by xopez** [comment]
Ah crap. I missed the message. Sorry for that.
`[TTT2][ERROR]Incompatible Add-On detected: TTT Identification Bomb + Defuser V2 (WS-ID: '305101059')`

**Comment by saibotk** [comment]
It just tells you, that this addon has known issues and is not supported. You should remove this from your collection.
