### ISSUE TITLE
SURVIVALIST has no shop

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#32]
SURVIVALIST has no shop. 
SURVIVALIST does not have the possibility of choosing your store, there is only a choice at another role, or disable, although it should be a choice like all other choices of his store with a choice for him personally weapons.
![image](https://user-images.githubusercontent.com/7480655/47970887-05702600-e0ad-11e8-900b-64efbb5d4d40.png)

As we can see, there is no possibility to choose your store on C

**Comment by dok441** [comment]
Noticed where it is written that they are involved in the innocent, then this role is not possible to choose your store, only if the use of others.

**Comment by Alf21** [comment]
Thank you very much, this has been a critical issue. If you disabled a shop, the possibility to use own shop disappears. To fix it temporary, select another option, close the window and reopen it :D

**Comment by Alf21** [comment]
Please check whether this is fixed.
The player models are involved by external add-ons I think. This shouldn't caused on TTT2
