### ISSUE TITLE
gs_crazyphysics no working

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#320]
Engine error: bmscientistcits\playermodel_male06.mdl (2) at -2.6 5.6 -4.8 in contact with bmscientistcits\playermodel_male06.mdl (2) at -2.5 5.4 -4.8, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000

Unfortunately, the system does not work properly, perhaps when you update it, it does not function properly and is due to skin crash when it was not before.

**Comment by Alf21** [comment]
You should post this issue here: https://github.com/Kefta/gs_crazyphysics
