### ISSUE TITLE
A spy that any fool can figure out.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#321]
В самом начале раунда, у предателя пишется в углу кто его предатель. Там шпиона нет, то есть его вычислить легко довольно, так-как сразу методом исключения из этих людей. Многие игроки жалуются и говорят, что тогда шпион ерунда и бесполезен, с одной стороны я их понимаю, что легко, но часто люди даже не внимательно смотрят, вот и я задаюсь вопросом, так должно быть или это все же недосмотрели с вашей стороны?

At the beginning of the round, a traitor is written in the corner who is a traitor. There's a spy there, that is to calculate it quite easily, so as at once a process of elimination of these people. Many players complain and say that then the spy is nonsense and useless, on the one hand I understand them that it is easy, but often people do not even look carefully, so I wonder, so it should be or is it still overlooked on your part?

**Comment by Alf21** [comment]
Should be fixed with the newest version. I didn't noticed it :D
