### ISSUE TITLE
Random Shop: Bestimmte Items immer haben

### ISSUE THREAD

**Issue by lasse2507c** [Alf21/TTT2#323]
Guten Abend,
Ich fände es wichtig, wenn man einstellen könnte, dass bestimmte Items (wie z.B. das Radar) im Random Shop immer zur Verfügung stehen.

Zusätzlich wäre es noch cool, wenn man bestimmten Items Wahrscheinlichkeiten, wie oft sie im Shop zur Verfügung stehen, zuteilen kann (diese Idee ist aber nicht so wichtig und soll daher bei zu hohem Aufwand nicht umgesetzt werden)

**Comment by derekstephen** [comment]
You can make certain items always show. Open the shop editor, press "edit items/weapons", then click on the item and make sure there is a check on "NoRandom".

![image](https://user-images.githubusercontent.com/7885194/56871475-7d7c3080-69ec-11e9-8222-b5bba3d925ec.png)


Sie können bestimmte Elemente immer anzeigen lassen. Öffnen Sie den Shop-Editor, klicken Sie auf "Gegenstände / Waffen bearbeiten", klicken Sie auf den Gegenstand und stellen Sie sicher, dass "NoRandom" aktiviert ist. Sorry, wenn das nicht die richtige Grammatik ist. Ich habe Google Translate benutzt.

**Comment by Alf21** [comment]
That‘s right, thanks @derekstephen !
