### ISSUE TITLE
Sprint using shift

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#33]
When using shift, the man runs very fast.

**Comment by Alf21** [comment]
Idk why you directly closed this. But it‘s seems to be an issue with the vampire. If you die as pigeon, you get faster all the time focused on sprint.

**Comment by dok441** [comment]
It's not about the vampire, me and everyone else, running fast after the round, but only I was a vampire.

**Comment by dok441** [comment]
Only that I was a vampire and ran very fast out of the use of a dove.

**Comment by Alf21** [comment]
Got it fixed with https://github.com/Alf21/ttt2-role_vamp/commit/5343a1fc23ee87855d602e55161bdcab68785625 ?

**Comment by dok441** [comment]
Kind of fixed.
