### ISSUE TITLE
Round do not Start

### ISSUE THREAD

**Issue by NeoRaiden** [Alf21/TTT2#330]
Hey have a Problem since over a year with ttt2 if i use Pointshop 2. Everytime after the preptime the prepphase dont end and following 2 Errors are in the console:
[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.1b] gamemodes/terrortown/gamemode/server/sv_main.lua:980: attempt to call global 'SelectRoles' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:980

Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 800)]

There is a optional Rolewightsystem in Pointshop 2 but it should be deactivated. For more Info feel free to contact me. The Serveradress is:  IP-Adresse: lptfun.hopto.org:27015 / Servername: [GER] LPTfun TTT twitch.tv/lptfun /  Serverpasswort: lptfun

**Comment by Alf21** [comment]
Should be irrelevant whether it‘s activated or not. It‘s there and seems to modify it. Try to remove it and maybe it works. If not, please list all your „DLC“s of PS2. Maybe you have the traitor passes or smth?

**Comment by NeoRaiden** [comment]
ok dont tried it until now because i want to keep the pointshop booster in this dlc but it worked thanks! I think it could be worse
