### ISSUE TITLE
attempt to perform arithmetic on field 'TipIndex' (a nil value)

### ISSUE THREAD

**Issue by Perwex** [Alf21/TTT2#331]
**Describe the bug**
Some players (every 5/6th player) receive an error as soon as they join the server.
They can't see hud and they can't use f1(settings), scoreboard.
In addition, they see a white window on the right.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to the server.
2. Just it.

**Expected behaviour**
1. HUD should work - it doesn't
2. F1 should open settings - it opens empty 
3. Tab should open scoreboard - it doesn't

**Screenshots**
Below. (cl_error)

**Desktop (please complete the following information):**
 - Collection-Link of your Server: Below (workshop.txt)
- Server and Client Errors are the same
`[ERROR] addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_lang.lua:75: bad argument #1 to 'rawget' (table expected, got nil)
  1. rawget - [C]:-1
   2. GetRaw - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_lang.lua:75
    3. SafeTranslate - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_lang.lua:82
     4. GetEquipmentTranslation - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/shared/sh_init.lua:244
      5. unknown - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_hudpickup.lua:20
[ERROR] addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:213: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. unknown - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:213
[ERROR] addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_lang.lua:68: attempt to index upvalue 'cached_active' (a nil value)
  1. GetTranslation - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_lang.lua:68
   2. Init - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:78
    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
     4. Create - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:259
      5. Show - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:269
       6. func - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_main.lua:397
        7. unknown - lua/includes/extensions/net.lua:32
[ERROR] addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:135: attempt to perform arithmetic on field 'TipIndex' (a nil value)
  1. NextTip - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:135
   2. unknown - addons/trouble_in_terrorist_town2(advancedupdate)-_v0.5.2b_1357204556/gamemodes/terrortown/gamemode/client/cl_tips.lua:242`

files:
[workshop.txt](https://github.com/Alf21/TTT2/files/3178763/workshop.txt)
[clientside_errors.txt](https://github.com/Alf21/TTT2/files/3178766/clientside_errors.txt)
![cl_error](https://user-images.githubusercontent.com/45741043/57713743-54f26880-7673-11e9-9648-bcab7457c498.jpg)

**Comment by TimGoll** [comment]
This is strange since the bug seems to be caused by the vanilla TTT tips in the bottom area. Do you know if these player might have disabled the tips?

**Comment by TimGoll** [comment]
Additionally to your line `--resource.AddWorkshop(1117144118) --ttt2 team buy ---------------doesn't work`: TTT/2 teambuy does work. This might be a problem on your side

**Comment by Alf21** [comment]
The tips are irrelevant. You have a incompatible addon. Maybe the wrong tttdamagelogs or the wrong specdm?

**Comment by TimGoll** [comment]
damagaelogs was my first thought as well because of the problem with the fifth player. But the error does look different than the typical damagelogs error

**Comment by TimGoll** [comment]
A tip for the future: please use a service like gist.github.com oder pastebin.com instead of textfiles

**Comment by Perwex** [comment]
I. Two people said they had turned on.
II. I turned off because one addon was shown as unknown without an icon
III. I have removed all addons and cache except ttt2 according to your suspicions and now it works.
Thank you for your time.

**Comment by Alf21** [comment]
Use my damagelogs instead. There is a hint in the ws and GitHub too :D

**Comment by Perwex** [comment]
I have installed your logs but they still do not work.

**Comment by Alf21** [comment]
To fix it finally, there need to be a reallocation of the PANEL (self var) and the cached tables ("cached_default ", "cached_active"). But as I said, this will just fix the error spam, not the primary error. @Dzwiedziasty
