### ISSUE TITLE
RandomShop Rerull per Buy - Error

### ISSUE THREAD

**Issue by D3thRoned** [Alf21/TTT2#336]
**Describe the bug**
Enabling randomshop_reroll_per_buy triggers console error and wont reroll

>[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.1b] gamemodes/terrortown/gamemode/server/sv_shop.lua:5: attempt to index local 'ply' (a nil value)^M
>  1. RerollShop - gamemodes/terrortown/gamemode/server/sv_shop.lua:5^M
>   2. unknown - gamemodes/terrortown/gamemode/server/sv_shop.lua:140^M
>    3. unknown -  lua/includes/modules/concommand.lua:54^M

**Potential Fix**
TTT2/gamemodes/terrortown/gamemode/server/sv_shop.lua:140

>if GetGlobalBool("ttt2_random_shop_reroll_per_buy") then
> RerollShop() // seem to need ply param
>end

**Comment by lebroomer** [comment]
Thank you for noticing, it is fixed now!
