### ISSUE TITLE
Disable symbol on TAB

### ISSUE THREAD

**Issue by Blaubeeree** [Alf21/TTT2#341]
Can you add a convar to enable and disable the server admin symbol on TAB?

**Comment by TimGoll** [comment]
yes! it is already planned. I just need to find some time to finish it

**Comment by TimGoll** [comment]
added in dev - commit 2c071a5d6aa4217ea9faf91647e33b8b0760d4a9

```
ttt_highlight_admins (vanilla TTT)
ttt_highlight_dev
ttt_highlight_vip
ttt_highlight_addondev
ttt_highlight_supporter
```
