### ISSUE TITLE
The npc killing Critical bug.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#355]
If you kill manchak, Pets, roller(NPC), now you do not die completely, and there is a bug, you can continue to talk and in the table you are still alive.

**Comment by dok441** [comment]
Also if the person died from the explosive barrels, I don't know, but it completely breaks the mode.

**Comment by TimGoll** [comment]
Maybe one of the other devs gets the situation described in this issue but I'm a bit confused. NPCs? Where are NPCs in TTT?

**Comment by dok441** [comment]
I described manhack for example, if you put them a traitor or some Pets, for example galanga can be done, it's simple =)

**Comment by dok441** [comment]
When approximately you will be able to correct it?

**Comment by TimGoll** [comment]
To be honest, I do not understand your problem and I'll wait if maybe someone else of the team does understand what to fix

**Comment by dok441** [comment]
Sorry of course, but again, if a person is killed for example barrel. He remains alive, though they should be dead, and he can talk with real people

**Comment by lebroomer** [comment]
Do you know if the same problem exists in Base TTT?

**Comment by TimGoll** [comment]
Yeah, this confuses me as well. I killed myself the last few days over and over again with explosive barrels. So this is bug is not related tp TTT2.

**Comment by dok441** [comment]
I've updated to the latest pre release version ТТТ2 and this problem appeared. Of course, I still check, but strange.

**Comment by TimGoll** [comment]
There were only UI changes in the last update, so this might be a coincidence
