### ISSUE TITLE
Suggestions to improve damagelogs role mapping.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#37]
Can do in damagelogs that showed who shoots from ttt2_sidekickdeagle Jackal. And that is the role that change in the game, and changed in the logs, but not so that a jester or an accomplice in the logs was a clown, not a role which it was issued, I would be grateful.

**Comment by Alf21** [comment]
Hmm. This definitely needs to be done. Idk when I have the time to do so...

**Comment by dok441** [comment]
Also, I believe, it is necessary to make that didn't appear offers of the complaint if you were killed by a jackal or the accomplice.

**Comment by Alf21** [comment]
In your language pls again :D

**Comment by dok441** [comment]
Так же в дополнения к этому, надо сделать в damagelogs чтоб не предлагало писать жалобы на доп.роли, к примеру если шакал кого-то убил и тд. После этого пишет, будто он RDM и предлагает написать жалобу.

**Comment by dok441** [comment]
Я хочу узнать, почему это не в приоритете, как администрировать сервер, если ты не знаешь, какая роль была у человека?! Тебе нужно ходить к гадалке?! Если допустим, человек ходил... Я полагаю, это должно быть в приоритете как очень важно и сделано в ближайшее время.

**Comment by Alf21** [comment]
It's not the high priority because this issue is not related to TTT2 itself. The problem is reasoned in damagelog. And it can just be fixed if damagelog supports role changing to display the current role at the situation of each event. But this CAN'T be solved in TTT2. We need to get Tommy involved or fix it on our own...

**Comment by dok441** [comment]
Я согласен с вами, но создатель damagelogs, больше не работает над своим аддоном, поэтому я полагаю, необходимо самим работать под адаптацию TTT2
