### ISSUE TITLE
The strangeness of the jester

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#38]
The clown the problem is, sometimes when he kills a traitor/innocent, then he is still a buffoon. But if you kill him, he will be Inno or a traitor, but he will not know and would not work. There are also times when he after 1 death, remains a buffoon, kill it again and then it becomes let's say a traitor, but the shop With, he will not have to work, and only write when you murder someone that you have been given credit for the store.

**Comment by SchokoShampoo** [comment]
download the adding winstates branch from github we are actually overworking the jester. He should be finished by now i will merge the two branches in next time

**Comment by SchokoShampoo** [comment]
Just merged it
