### ISSUE TITLE
Additional cost of items from shop C

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#39]
Would like to suggest to make possible to set the value of the object to buy traitor/detective, and so on. So as now all the items cost 1 credit, I would like to install 2 or more credits for something, for example a defibrillator detective 2 credits and so on, so you can add interesting things and increase their cost, so that people chose different as his possibility. This will make the gameplay more interesting and allow you to add more interesting things to active roles.

**Comment by Alf21** [comment]
That‘s possible, sure, but it will get included in the new weaponshop
