### ISSUE TITLE
Bug Instead of an innocent, a traitor.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#42]
For some reason, the role of the person together innocent, became a traitor on the definition of roles, in the logs or on the player to direct, he was a traitor, but on the logs innocent. He could do the same thing as a traitor. After that, an error in the logs for this round began to appear. It was held after the end of the next round.
![wa](https://user-images.githubusercontent.com/7480655/48141273-5c077b00-e2cc-11e8-8431-e51a3c884ee0.png)

[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 64
  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadType - lua/includes/extensions/net.lua:121
     4. ReadTable - lua/includes/extensions/net.lua:124
      5. func - addons/tttdamagelogs-master/lua/damagelogs/client/tabs/damagetab.lua:466
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by Alf21** [comment]
Are you using damagelog copied from my GitHub Repo?

**Comment by dok441** [comment]
yes

**Comment by Alf21** [comment]
okay, but 1) I couldn't read this, could you send a screenshot in English? and 2) this here is the TTT2, not the tttdamagelog addon ;) It's really hard to understand what you want to say. I really can't understand the situation that is caused this problem, but I will try to find any bug belong to this lines of code...

**Comment by dok441** [comment]
невиновный - innocent
активирует - Activates
Урон - damage
I tried to request your damagelogs, but there option is disabled. I mean, he was innocent in the logs, but he was a traitor, the logs were lies.

**Comment by dok441** [comment]
Well, send, you can see above, I also zaskrinil what his role was originally issued and it is innocent by damagelogs

**Comment by Alf21** [comment]
Hmm, could you close this (because it‘s a part of the RDM Manager). I don‘t have this issue so maybe you have some incompatible add-ons?
