### ISSUE TITLE
The notification to the accomplice from a jackal

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#43]
Is it possible to make some notification with the Jackal's Sidekick Deagle when he turns someone into Sidekick? For example: (at the center of the screen) «You are now a Sidekick! <Nick> is your master. Kill all others!». Because I often see that Sidekick can almost immediately kill Jackal by accident. In my opinion, the best option is to add notification and disable friendly fire on 30 seconds after Jackal turns someone into Sidekick.

**Comment by Alf21** [comment]
Sure, i could easily add this. The question is how to solve this. Freezing the player ist visible by others. Disabling team damage could cause in wrong results. Maybe disabling team damage for 1s could help to reduce situations resulted in affect.

**Comment by SchokoShampoo** [comment]
There is now a Convar which will be added to ulx soon.
With the ConVar ttt2_siki_protection_time you can change the time the protection is active
Standard time is 1 sec

**Comment by SchokoShampoo** [comment]
Please close if this is ok with you

**Comment by dok441** [comment]
okey
