### ISSUE TITLE
Untrue report of a hitman

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#44]
![image](https://user-images.githubusercontent.com/7480655/48163720-3c8b4500-e302-11e8-9896-955dc7325a20.png)

When at the person merge and he has a role Hitman and he dies, in a chat reports that it was hitman and killed not that...

**Comment by Alf21** [comment]
Pls try to send it in your original language again ^^

**Comment by Alf21** [comment]
Do you mean that if a hitman dies, he gets revealed? Or do you mean that if another player dies, the hitman gets revealed?

**Comment by dok441** [comment]
Если он умирает от админской команды "slay", то пишет в чат, что он будто убил кого-то и выдал себя, хотя он просто умер

**Comment by SchokoShampoo** [comment]
Ok we got the mistake and will fix it

**Comment by SchokoShampoo** [comment]
should be fixed now
can you test it and close the issue afterwards?

**Comment by dok441** [comment]
Снова баг этот есть

**Comment by Alf21** [comment]
How do you slay people? You mean, if you are a hitman and slay people, your role will be revealed. That's logical because you are the killer if you slay someone...

**Comment by dok441** [comment]
At delivery of slay by the administrator.

**Comment by Alf21** [comment]
I mean which add-on?

**Comment by dok441** [comment]
Which of damagelogs alsays

**Comment by Alf21** [comment]
As far as I know, @SchokoShampoo will fix this soon :)

**Comment by dok441** [comment]
Да. Так же когда человек умирает, это тоже сообщает в чат, что он убил не того.

**Comment by SchokoShampoo** [comment]
Do you mean a message like "SchokoShampoo has been autoslain by Alf21 5 min ago with the reason: teamkill"?

**Comment by SchokoShampoo** [comment]
Is fixed
also it shouldnt happen anymore, because the aslay command now supports ttt2 roles and prevents the selection of a special role
