### ISSUE TITLE
adaptation HUD

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#46]
Hello, I would like that you made adaptation of this HUD https://my-files.ru/uop4p3

**Comment by Alf21** [comment]
Hmmm... i‘m just able to modify open sourced code, so something that got published to the public in GitHub, garrysmod or the Steam Workshop.

**Comment by Alf21** [comment]
Because I‘m uploading all of my add-ons to make them public. I don‘t have enough time to do individual work. That‘s the reason...
