### ISSUE TITLE
ERROR coonect

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#47]
При входе на сервер или же при открытии !menu, выскакивает эта ошибка. Из-за этой ошибки не работает в !menu отдел истории банов, в остальном просто спам ошибки. Появилась это ошибка после последнего вашего обновления беты, возможно здесь есть моя вина, но я вроде ничего не делал серьезного.

[ERROR] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value)
  1. Call - lua/includes/modules/hook.lua:120
   2. fn - addons/ulib/lua/ulib/cl_init.lua:58
    3. func - addons/ulib/lua/ulib/client/cl_util.lua:22
     4. unknown - lua/includes/extensions/net.lua:32

ULib queue error: lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value)

Так же бывает пишет при открытии !menu

[ERROR] lua/includes/modules/hook.lua:120: attempt to index a string value with bad key ('UCLAuthed' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. Call - lua/includes/modules/hook.lua:120
     4. fn - addons/ulib/lua/ulib/cl_init.lua:58
      5. func - addons/ulib/lua/ulib/client/cl_util.lua:22
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by dok441** [comment]
P.S после смены карты прошло, но по какой причине тогда эта ошибка была...

**Comment by Alf21** [comment]
Hm, i never noticed anything like this... is it resulted in the map? This error doesn‘t have anything to do with TTT2 or the menu addon, it‘s caused from Ulib. Idk why this happen o.O

**Comment by dok441** [comment]
Возможно с моей стороны что-то, но у клиента рандомно это происходит. У меня прошло, но у кого-то я замечаю в логах пишет такое.

**Comment by Alf21** [comment]
Hmm... but as I said, that‘s not an issue of TTT2. It’s an rare issue of Ulib that shouldn’t happen. Maybe he is using bad tools to modify gmod ;)
