### ISSUE TITLE
Traitors have all Items

### ISSUE THREAD

**Issue by BoostedDampi** [Alf21/TTT2#48]
The Traitors have all items from all shops and the SpectatorDM and we can´t find the Sidekick deagle in the Jackal shop, but in the Traitor shop

The error
https://screenshots.freezzer.com/mstsc_2018-11-08_20-10-39.png

https://steamuserimages-a.akamaihd.net/ugc/969858026272394690/D690058FA89609285F4D8CDFB629389248D18E39/)
(https://steamuserimages-a.akamaihd.net/ugc/969858026272394301/4781C02F735D0099AB7672A58589AA36492ABB99/)

**Comment by Alf21** [comment]
Okay ty, I fixed the issue with the unpooled net message, was an artefact.
Maybe you've added all items to the traitor shop in the weaponshop? :D

**Comment by BoostedDampi** [comment]
No, i only Subsribe and add the addons to the server

**Comment by Alf21** [comment]
I meaned if someone changed your weaponshop (type in "weaponshop" as a command)

**Comment by BoostedDampi** [comment]
Ahh ok sry xD, No, I don’t edited that, and the strange thing is that this problem occurred only when the TTT2 Beta addon is installed

**Comment by Alf21** [comment]
I‘m unable to reproduce. Maybe you‘ve added all the items per weaponshop into the traitor shop (using own shop option).
