### ISSUE TITLE
Adaptation of weapon in weaponshop

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#49]
https://github.com/Fortune117/DiscreteTTTAddons/blob/master/fortunes_weapons_ttt/lua/autorun/sh_equipment.lua
You can adapt Tesla Shield, he doesn't see such weapon and doesn't add to your system.

**Comment by dok441** [comment]
https://github.com/Alf21/ttt-weapon_cloakingdevice Also it isn't visible in your weaponshop shop and the role isn't given.

**Comment by dok441** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=236217898&searchtext=deathfaker Баг с выбором ролью, всегда выпадает твоя роль, а не роль которую ты выбрал.

**Comment by Alf21** [comment]
> Баг с выбором ролью, всегда выпадает твоя роль, а не роль которую ты выбрал.

There is already a compatible add-on made by LeBroomer

**Comment by Alf21** [comment]
> 
> 
> https://github.com/Alf21/ttt-weapon_cloakingdevice Also it isn't visible in your weaponshop shop and the role isn't given.

should work now, but my CloakingDevice is an old one.



> 
> 
> https://github.com/Fortune117/DiscreteTTTAddons/blob/master/fortunes_weapons_ttt/lua/autorun/sh_equipment.lua
> You can adapt Tesla Shield, he doesn't see such weapon and doesn't add to your system.

I won't do this because this item will lead into lags (as you told me in https://github.com/Alf21/TTT2/issues/204)

**Comment by dok441** [comment]
Tesla Shield вы поддержку сделайте таких предметов как Tesla Shield, так-как они просто не появляются в shop. Он их просто не видит.

**Comment by Alf21** [comment]
Yea because they are loading in an not understandable way. I could fix this, but first of all I need the Workshop Resource and need to communicate with the author
