### ISSUE TITLE
Infected the notice as at a jackal

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#50]
Предлагаю сделать уведомление, когда тебя убивает зараженный, а то так же как и с шакалом некоторые убивают главного зараженного, а вообще лучше будет здесь отключить урон помощникам зараженного, так-как они с ножами и выглядят как зомби, тут ничего странного в этом не будет

**Comment by Alf21** [comment]
I don‘t think it is necessary because if you die as infected, you get revived after 3 seconds. In this time, the main infected can‘t damage you and you can think about the situation to avoid damaging the main. ;)

**Comment by dok441** [comment]
The assistant to infected can kill the main thing infected, at me already 3 times was for today it.

**Comment by Alf21** [comment]
Haha sorry, but that‘s just dump and that ist the result ^^ If the assistant kills the main, that‘s teamkilling simply and needs to get punished. It would be the same as killing your mate as traitor. In addition to that, it‘s a way more harder to kill someone with a knife so...

**Comment by dok441** [comment]
А смысл это разрешать? Это зомби, их все знают в лицо, они не играют в детективную игру, главного своего хозяина они не могут выдать, так-как они итак его не могут трогать, иначе убьют, просто это очередная лазейка для идиотов которые не знают правила или тупые и промахиваются =) Вы подумайте, зачем давать им разрешение на командное убийство? Довольно легко в сумбурности задеть, это практика показала, в маленьких особенно помещениях, я уж молчу о том, что они не понимают, что они стали зараженными, слишком для них сложно, тут нужно упрощать, дети = зло -(

**Comment by Alf21** [comment]
Okay after discussing pro and cons, this will NOT be implemented. I don‘t create an anticheat or a rdm manager. There you can use other tools. If i would implement it, it would also need to disable teamdamage for any oher role. That‘s useless. The only thing we can think about is to punish the attackers by lowering their scores and karma much more.
