### ISSUE TITLE
Infected with weapon

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#51]
Теперь помощники зараженного, могут носить и использовать оружие кроме ножа. Это началось после обновления роли или режима, тут я не могу сказать точно,

**Comment by Alf21** [comment]
Should be fixed

**Comment by dok441** [comment]
Это исправлено. Но, оружие после смерти с зомби выпадает, а это куча ножей, с помощью них люди могут легко убивать кого угодно, может сделать, чтоб после смерти зомби, ножи не выкидывались?

**Comment by Alf21** [comment]
Yea, I will implement a weapon

**Comment by Alf21** [comment]
The infected should have an own weapon now.

**Comment by Alf21** [comment]
Then don‘t forget to close it ;)
