### ISSUE TITLE
Bug of the shop infected.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#52]
При открытии магазина у зараженного появилась такая ошибка.
[TTT2] gamemodes/terrortown/gamemode/cl_equip_main.lua:290: attempt to call method 'IsEquipment' (a nil value)
  1. unknown - gamemodes/terrortown/gamemode/cl_equip_main.lua:290
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by Alf21** [comment]
Why you closed this?

**Comment by dok441** [comment]
Полагаю, что причины была на моей стороне.
