### ISSUE TITLE
Unkown bug dead

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#53]
Меня убили, когда моя роль была неизвестный, но после этого я не возродился.
![bug unkown](https://user-images.githubusercontent.com/7480655/48285855-b39d1680-e485-11e8-8eb1-eceb1f34a853.png)

**Comment by Alf21** [comment]
When will this happen? Explain the situation please :)

**Comment by Alf21** [comment]
Should be fixed. But in the future, this can happen if there is no player as an attacker, e.g. because you got killed by a buggy weapon that doesn't handle the attacker in the right way.

**Comment by Alf21** [comment]
Then don‘t forget to close it ;)
