### ISSUE TITLE
Bug with the notice of a role

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#54]
Когда я определил труп survivalist, то мне написало в центре уведомление, мне выпала роль survivalist как в самом начале.

**Comment by Alf21** [comment]
Do you mean that the role animated notification is shown while searching / identifying a player?

**Comment by Alf21** [comment]
Fixed :)

**Comment by dok441** [comment]
No, the problem is even after your updating if it of course isn't connected with a mistake and this problem not of a reshan yet in any way.

**Comment by dok441** [comment]
Я когда шёл, мне написало выживший, я был предателем, кто-то определил труп видимо.

**Comment by Alf21** [comment]
hmmm... I will try to repeat, but it should be fixed in the last ttt2-animation commit

**Comment by dok441** [comment]
Теперь вообще, начинает писать разные роли даже в начале раунда, нужно исправлять =)

**Comment by Alf21** [comment]
Did you update the ttt2-animations add-on? With the latest fixes, I was not able to reproduce this. It must be caused by your setup.

**Comment by Alf21** [comment]
hmm... there is still an issue. It's caused on the networking. I will improve it to fix this issue and improve performance.
