### ISSUE TITLE
2 accomplices, one bullet

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#55]
У шакала есть баг с его оружием weapon_ttt2_sidekickdeagle.lua только, что шакал превратил 2 человек в сообщников, я не знаю каким образом, вроде мы шли цепочкой, но я протестировал еще раз, но это не повторилось, но возможность такая есть, это факт.

**Comment by Alf21** [comment]
Hmm.. up to now, I will close this issue until it doesn‘t happen again. Theoretically, this is impossible. But it‘s possible to have more than one sidekick.
