### ISSUE TITLE
After updating writes a mistake.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#56]
[ERROR] addons/animations/lua/autorun/rv_init.lua:113: bad argument #1 to '(for generator)' (table expected, got nil)
  1. (for generator) - [C]:-1
   2. func - addons/animations/lua/autorun/rv_init.lua:113
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by SchokoShampoo** [comment]
This was a bug in the process and will be fixed later so i will close this issue
