### ISSUE TITLE
vampire blod start game

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#61]
Бывает, что при появлении ролью вампир, жажда крови сразу на нуле и начинает тратиться HP. Хотя ты ничего не делал.

**Comment by Alf21** [comment]
Please explain the situation in detail :)

**Comment by dok441** [comment]
Каждый раунд ты будучи вампиром сразу начинаешь терять здоровье и у тебя включена жажда крови

**Comment by Alf21** [comment]
Hmmm.. I changed the system a little bit. Is it fixed? You know that you will force into Bloodlust by clicking the ALT key?

**Comment by dok441** [comment]
Знаю. Позже отпишу, исправлено или нет.

**Comment by Alf21** [comment]
Is it fixed?

**Comment by dok441** [comment]
Баг все еще появляется иногда.

**Comment by Alf21** [comment]
Curious. Can't even reproduce... Some more information or a video? This theoretically can't happen because there isn't any lack of code regarding hooks, that are made by gmod and should work properly.
