### ISSUE TITLE
Bug with display of the status

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#62]
Теперь после обновления, если вы выставляете статус подозрительный к примеру в TAB, то на игроке это не отображается.

**Comment by Alf21** [comment]
Could you send a screenshot of the situation it should be? Or explain in more detail?

**Comment by dok441** [comment]
![23](https://user-images.githubusercontent.com/7480655/48349650-a743d400-e6a6-11e8-9d06-7d31d1aac832.png)
Вы выставляете подозрительный к примеру и если наводить на игрока, эта надпись должна появляется на нем, но её нету. Вы поняли о чем я?
