### ISSUE TITLE
Weaponshop bug sync

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#69]
После обновления, происходит баг. Именно если ты меняешь карту все предметы сбрасываются у ролей и необходимо снова нажимать  "Выключить магазин", а потом "use own shop" чтоб предметы активировались у роли.

**Comment by Alf21** [comment]
Okay. You mean this appears if I change my shop into „Use own Shop“. After that, i change the map. Then, the shop is empty and I need to reset it (disable and enable). Am i right?

**Comment by dok441** [comment]
Проще говоря, как вы сказали, только выключить и выбрать свой магазин снова и тогда предметы загружаются, но после смены карты их снова нет.

**Comment by Alf21** [comment]
Yea I reproduced it. I will rewrite the weaponshop system

**Comment by dok441** [comment]
thanks

**Comment by Alf21** [comment]
Could you do some tests? I don't know whether the switch between own shop and default equipment or linking shops is working

**Comment by dok441** [comment]
Теперь все нормально.

**Comment by dok441** [comment]
Есть другой баг теперь, если ты пытаешься добавить оружие, которого не было у роли добавлено до этого и меняешь карту, оно не сохраняется. В папке файл не появляется.

**Comment by dok441** [comment]
А, нет, надо было удалить старую базу данных, теперь вроде нормально.
