### ISSUE TITLE
new Role Undertaker

### ISSUE THREAD

**Issue by TheSuspect2306** [Alf21/TTT2#70]
Undertaker:

- its like jackal with the sidekick deagle, but the undertaker can defibrillate guys with the defibrillator to his team

- undertaker can defibrillate max 1 player to his team OR he can infinite defibrillate players but they spawn with lower hp or can only pickup pistols or have only fists or something

- (has a own shop)

**Comment by Shaknunic** [comment]
If you want to do that, just put the a defibrillator item in one of the roles already existing and put to limit that item, it will work as well... In resume this role is useless...

**Comment by SchokoShampoo** [comment]
The Role is now available for testing here: https://github.com/TTT-2/ttt2-role_ut

**Comment by TheSuspect2306** [comment]
error at line 230 just replace ply:SetHealth(GetMaxHealth()) with ply:SetHealth(ply:GetMaxHealth())

**Comment by Alf21** [comment]
Yea a zombie model and infinite revive (while losing 15hp/20hp per revive?) would be great :D

**Comment by TheSuspect2306** [comment]
i think a random number between 50 and 100 hp

**Comment by SchokoShampoo** [comment]
> 
> 
> can you make them like a zombie, give the player a zombie model and they can only fist players to death ? and infinite revive ?

wouldn't that go in the direction of the infected?

**Comment by TheSuspect2306** [comment]
yea its like the infected role

**Comment by dok441** [comment]
Как вам идея, заменить дефибриллятор на  ритуал жертвоприношения? https://github.com/Fortune117/DiscreteTTTAddons/blob/master/fortunes_weapons_ttt/lua/weapons/weapon_ttt_ritual/shared.lua Думаю, это будет интересней и красивее, чем обычное возрождения и сделать, чтоб человек который возрождает жертвовал 20 hp возрождая товарища с 50 hp.

**Comment by SchokoShampoo** [comment]
I have a tight schedule at the time so it could take some time, until i can update the role.
Could you join the discord server? Sometimes problem solving is faster this way

**Comment by TimGoll** [comment]
I'm closing this for now since it won't be implemented as it is basically the same as the necromancer for dhalucard. The necromancer will be released at some point this year.
