### ISSUE TITLE
edn round

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#71]
[TTT2 BETA + all TTT2 add-ons] gamemodes/terrortown/gamemode/cl_awards_main.lua:594: attempt to perform arithmetic on field 'tk' (a nil value)
  1. afn - gamemodes/terrortown/gamemode/cl_awards_main.lua:594
   2. BuildHilitePanel - gamemodes/terrortown/gamemode/cl_scoring_main.lua:387
    3. ShowPanel - gamemodes/terrortown/gamemode/cl_scoring_main.lua:457
     4. ReportEvents - gamemodes/terrortown/gamemode/cl_scoring_main.lua:584
      5. func - gamemodes/terrortown/gamemode/cl_scoring_main.lua:614
       6. unknown - lua/includes/extensions/net.lua:32

В конце раунда выскакивает.

**Comment by Alf21** [comment]
I already noticed, but thanks. This happens while fixing an unreported scoreboard issue as well as an unreported weaponshop issue.
