### ISSUE TITLE
The player is not defined

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#72]
Когда убили человека, при осмотре его, человек не определяется как мертвый в табе, он просто остается неизвестным.

**Comment by dok441** [comment]
![222](https://user-images.githubusercontent.com/7480655/48500553-f6cc0080-e85c-11e8-9c3f-df25de397c97.png)
Пытаясь его определить ничего не происходит.

**Comment by Alf21** [comment]
Ahhhhh, now I understand :D Will to be fixed in 5mins

**Comment by Alf21** [comment]
Did you pressed [E] and after that the confirm button?

**Comment by dok441** [comment]
yes

**Comment by Alf21** [comment]
> Когда наводишь на человек, используя маскировку личности, выдает ошибку:
> [TTT2 BETA + all TTT2 add-ons] gamemodes/terrortown/gamemode/cl_targetid_main.lua:224: attempt to call method 'IsSpecial' (a nil value)
> 
> 1. Call - gamemodes/terrortown/gamemode/cl_targetid_main.lua:224
> 2. unknown - gamemodes/terrortown/gamemode/cl_hud_main.lua:331

Lol, this error can't occur / exist :D

**Comment by dok441** [comment]
> > Когда наводишь на человек, используя маскировку личности, выдает ошибку:
> > [TTT2 BETA + all TTT2 add-ons] gamemodes/terrortown/gamemode/cl_targetid_main.lua:224: attempt to call method 'IsSpecial' (a nil value)
> > 
> > 1. Call - gamemodes/terrortown/gamemode/cl_targetid_main.lua:224
> > 2. unknown - gamemodes/terrortown/gamemode/cl_hud_main.lua:331
> 
> Lol, this error can't occur / exist :D

Это происходит со сменой личностью человек, когда он пытается одеть личность неопределенного трупа=) Поэтому такая ошибка =)

**Comment by Alf21** [comment]
Should be fixed. You need to move closer to toggle the search screen. If you want to have the old auto-confirming system, toggle the "ttt_identify_body_woconfirm" into "1"
