### ISSUE TITLE
ulx admin

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#90]
![123](https://user-images.githubusercontent.com/7480655/48650771-6a1a7180-ea19-11e8-8c31-2c6af57b376d.png)
При попытке выбора, пишет в консоль ERROR

**Comment by Alf21** [comment]
I will check this in 2 days :)

**Comment by Alf21** [comment]
Should be fixed. Forcing a role for the next round just happen if the role is selectable focussed on the number of players and just if the role is enabled.

**Comment by Alf21** [comment]
I've added a hard forcing option to get the role definitely.
