### ISSUE TITLE
jester jesus

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#91]
![5555](https://user-images.githubusercontent.com/7480655/48660682-98cf3100-ea87-11e8-90f3-1f6bd63ddd32.png)
Упал на rooftops вниз карты где должен был умереть, а ему по богу.

**Comment by dok441** [comment]
Хотя с другой стороны это правильно.

**Comment by Alf21** [comment]
Yea, i really understand what you mean. We already discussed about it and came to this result. Another solution have been to kill the jester without triggering any winstate. The problem on the other side: Many add-ons (weapons) doesn‘t trigger an attacker and the damage is handled as world damage. So this wouldn‘t work properly. So, Schoko decided to keep him alive and getting punished for this fault or stupidness :D
