### ISSUE TITLE
0 credit T

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#92]
У предателей(вампир,хитман) нету изначально кредитов.

**Comment by dok441** [comment]
Надо самому исправлять в конфиге

**Comment by dok441** [comment]
Так же не дают кредиты за убийство детектива

**Comment by dok441** [comment]
Конфигурация не работает.

**Comment by Alf21** [comment]
Okay, that‘s a bug definitely, ty, will fix it tomorrow!

**Comment by Alf21** [comment]
I tested and it works properly...

**Comment by dok441** [comment]
У хитмана все еще нету кредитов.

**Comment by dok441** [comment]
Если прописать зараженному, у него не будет кредитов как и у хитмана.

**Comment by dok441** [comment]
thanks
