### ISSUE TITLE
jesus PropKILL

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#93]
Необходимо запретить jester поднимать предметы или сделать так, чтоб он не мог убить пропом, так-как, он может спокойна пропкилить.

**Comment by Alf21** [comment]
How can we reproduce it?
I tried throwing a prop against a player and to explode a barrel next to a player as a jester, but the player didn't receive any damage.

**Comment by dok441** [comment]
Ну обычный проп, как пропкилите вы? Если вы не умеете пропкиллить, то не получится =) Попробуйте невиновным взять бочку обычную и с разворота кинуть, тут так же.

**Comment by Alf21** [comment]
Haha I did it :D I‘m not the best skill shooter, but I‘ve an add-on that shows an indicator, if you hit another player. This indicator got shown, but the player didn‘t lost any hp. Why not creating a video, would be entertainment as well :D

**Comment by SchokoShampoo** [comment]
So now the Jester can't pick up props so easily. They are heavier for the Jester. Please try and tell us what you think.

**Comment by dok441** [comment]
thanks
