### ISSUE TITLE
Bug chat exit

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#94]
![3333](https://user-images.githubusercontent.com/7480655/48661756-ffa91600-ea98-11e8-807b-6b9ea31ab8eb.png)
При попытке выйти из чата ничего не происходит, я бы написал разработчику логов, но он уже давно ничего не делает,  и я использую вашу версию damagelogs, а она сильно отличается от оригинальной, было бы хорошо, если бы вы исправили этот баг, когда будете заниматься damagelogs с другими моими предложениями.

**Comment by Alf21** [comment]
Hmm... to keep it clear, please post a link to your suggestion (the other post), so that we can handle it there. This have no connection to TTT2 so i would like to talk about it externally. We can think about it, but currently i don‘t have a lot of time :/
