### ISSUE TITLE
Death Faker BUG?

### ISSUE THREAD

**Issue by Kryben** [Alf21/TTT2#97]
Hi, gutes update vom Addon, danke dafür.

Jedoch haben wir seit dem Update nun den Bug das zbsp beim Death-Faker in klammern immer die echte Rolle angezeigt wird. Beim Deadringer wird zbsp nur (TEAM) angezeigt wenn man identifiziert 

https://prnt.sc/ljnyrj

Ist das ein BUG oder muss ich zusätzlich etwas einstellen?

LG

**Comment by Alf21** [comment]
Das ist definitiv ein Bug. Wird wohl darauf hinauslaufen, dass ich meinen eigenen Deathfaker und Deathringer direkt in TTT2 integriere...

**Comment by Tobiti** [comment]
Würde es nicht reichen, wenn man beim Identifizieren das Team weg lässt?

**Comment by Alf21** [comment]
Ja, schon. Aber man will doch wissen, in wessen Team der Spieler war oder nicht? Gerade im Bezug auf den Sidekick

**Comment by Tobiti** [comment]
Ich glaube meistens reicht es zu wissen, das ein Sidekick da ist und nicht zu welchen Team er gehört. Und für den Anfang würde ich vorschlagen einfach allen die Möglichkeit zu geben, dass man die die Anzeige des Teams an und abschalten kann :)
