### ISSUE TITLE
Confirmation of death, duplication

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#99]
https://steamuserimages-a.akamaihd.net/ugc/951844356901884216/352D5B15035169A31AD6CDBDBB38191CBB45CF5A/

Как мы можем увидеть, пишет очень много раз о подтверждении трупа, как это вызывать не знаю, мне сообщили самому.

**Comment by dok441** [comment]
Так же бывает, когда ты опознаешь 1 труп, пишет всем, что ты опознал другой. 
![3333](https://user-images.githubusercontent.com/7480655/48676371-c4d1db80-eb87-11e8-871b-db862fe79019.png)

**Comment by Alf21** [comment]
Hmm, I never saw message spams like this... We need more information about the situation this happens.

There is an option "ttt2_identify_body_woconfirm". Toggle this to just confirm for everyone on clicking "confirm".

**Comment by dok441** [comment]
Установлено ttt_identify_body_woconfirm 1 у меня.

**Comment by dok441** [comment]
Я нашел тело этого игрока, а написало всем, будто я нашел другое тело.

**Comment by Alf21** [comment]
As i said, toggle "ttt_identify_body_woconfirm" to "0" if you don't want it ^^
